// packages/vue/src/Accordion.vue
<template>
  <div class="ctp-accordion" :data-variant="variant" :data-color="colorMode !== 'none' ? colorMode : undefined" :data-accent="accentColor" v-bind="$attrs">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed, provide, ref, watch } from 'vue';

type AccordionVariant = 'default' | 'split';
type AccordionColorMode = 'none' | 'colored' | 'tonal';
type AccordionAccentColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';

interface Props {
  variant?: AccordionVariant;
  colorMode?: AccordionColorMode;
  accentColor?: AccordionAccentColor;
  allowMultiple?: boolean;
  modelValue?: string | string[];
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'default',
  colorMode: 'none',
  allowMultiple: false,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: any): void;
}>();

const openValues = ref<string[]>([]);

watch(
  () => props.modelValue,
  (newVal) => {
    if (newVal !== undefined) {
      openValues.value = Array.isArray(newVal) ? newVal : [newVal];
    }
  },
  { immediate: true, deep: true }
);

const toggleValue = (value: string) => {
  let nextValues: string[];
  if (props.allowMultiple) {
    nextValues = openValues.value.includes(value)
      ? openValues.value.filter((v) => v !== value)
      : [...openValues.value, value];
  } else {
    nextValues = openValues.value.includes(value) ? [] : [value];
  }
  openValues.value = nextValues;
  emit('update:modelValue', props.allowMultiple ? nextValues : (nextValues[0] || ''));
};

provide('accordion', {
  openValues,
  toggleValue,
  colorMode: computed(() => props.colorMode),
  accentColor: computed(() => props.accentColor),
});
</script>

// packages/angular/src/accordion.component.ts
import { Component, input, computed, output, signal, effect, inject } from '@angular/core';

export type AccordionVariant = 'default' | 'split';
export type AccordionColorMode = 'none' | 'colored' | 'tonal';
export type AccordionAccentColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';

@Component({
  selector: 'ctp-accordion',
  standalone: true,
  template: `
    <div class="ctp-accordion"
      [attr.data-variant]="variant()"
      [attr.data-color]="colorMode() !== 'none' ? colorMode() : null"
      [attr.data-accent]="accentColor() || null"
    >
      <ng-content></ng-content>
    </div>
  `
})
export class CptAccordionComponent {
  variant = input<AccordionVariant>('default');
  colorMode = input<AccordionColorMode>('none');
  accentColor = input<AccordionAccentColor | undefined>(undefined);
  allowMultiple = input<boolean>(false);
  activeValues = input<string | string[]>([]);

  activeValuesChange = output<string | string[]>();

  private openValuesSignal = signal<string[]>([]);
  openValues = this.openValuesSignal.asReadonly();

  constructor() {
    effect(() => {
      const externalVal = this.activeValues();
      const nextVal = Array.isArray(externalVal) ? externalVal : (externalVal ? [externalVal] : []);
      const currentVal = this.openValuesSignal();
      const hasChanged = currentVal.length !== nextVal.length || !currentVal.every((v, i) => v === nextVal[i]);
      if (hasChanged) {
        this.openValuesSignal.set(nextVal);
      }
    }, { allowSignalWrites: true });
  }

  toggleValue(value: string) {
    const current = this.openValuesSignal();
    let next: string[];
    if (this.allowMultiple()) {
      next = current.includes(value)
        ? current.filter(v => v !== value)
        : [...current, value];
    } else {
      next = current.includes(value) ? [] : [value];
    }
    this.openValuesSignal.set(next);
    this.activeValuesChange.emit(this.allowMultiple() ? next : (next[0] || ''));
  }
}

@Component({
  selector: 'ctp-accordion-item',
  standalone: true,
  template: `
    <div class="ctp-accordion-item" [attr.data-state]="isOpen() ? 'open' : (disabled() ? 'disabled' : null)">
      <button
        type="button"
        class="ctp-accordion-header"
        [disabled]="disabled()"
        [attr.aria-expanded]="isOpen()"
        (click)="handleHeaderClick()"
      >
        <span class="ctp-accordion-title">
          @if (title()) {
            {{ title() }}
          }
          <ng-content select="[header]"></ng-content>
        </span>
        @if (showChevron()) {
          <svg
            class="ctp-accordion-chevron"
            viewBox="0 0 24 24"
          >
            <polyline points="6 9 12 15 18 9" />
          </svg>
        }
      </button>

      <div
        class="ctp-accordion-collapse"
        [attr.aria-hidden]="!isOpen()"
      >
        <div class="ctp-accordion-content">
          <div class="ctp-accordion-body">
            <ng-content></ng-content>
          </div>
        </div>
      </div>
    </div>
  `
})
export class CptAccordionItemComponent {
  value = input.required<string>();
  title = input<string | undefined>(undefined);
  disabled = input<boolean>(false);
  showChevron = input<boolean>(true);

  private accordion = inject(CptAccordionComponent, { optional: true });

  isOpen = computed(() => {
    if (!this.accordion) return false;
    return this.accordion.openValues().includes(this.value());
  });

  handleHeaderClick() {
    if (this.disabled() || !this.accordion) return;
    this.accordion.toggleValue(this.value());
  }
}
