// packages/react/src/Command.tsx
import React, { useState, useRef, useEffect, useCallback } from 'react';
import ReactDOM from 'react-dom';

export interface CommandItem {
  id: string;
  label: string;
  icon?: React.ReactNode;
  shortcut?: string;
  group?: string;
  onSelect?: () => void;
}

export interface CommandProps {
  items: CommandItem[];
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  placeholder?: string;
  emptyMessage?: string;
  className?: string;
}

export const Command: React.FC<CommandProps> = ({
  items,
  open: controlledOpen,
  onOpenChange,
  placeholder = 'Search commands...',
  emptyMessage = 'No results found.',
  className = '',
}) => {
  const [uncontrolledOpen, setUncontrolledOpen] = useState(false);
  const isControlled = controlledOpen !== undefined;
  const isOpen = isControlled ? controlledOpen : uncontrolledOpen;

  const [query, setQuery] = useState('');
  const [selectedIndex, setSelectedIndex] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);
  const listRef = useRef<HTMLDivElement>(null);

  const setOpen = useCallback((open: boolean) => {
    if (!isControlled) setUncontrolledOpen(open);
    onOpenChange?.(open);
    if (open) {
      setQuery('');
      setSelectedIndex(0);
    }
  }, [isControlled, onOpenChange]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        setOpen(!isOpen);
      }
      if (e.key === 'Escape' && isOpen) {
        setOpen(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, setOpen]);

  useEffect(() => {
    if (isOpen) {
      setTimeout(() => inputRef.current?.focus(), 50);
    }
  }, [isOpen]);

  const filtered = items.filter(item =>
    item.label.toLowerCase().includes(query.toLowerCase())
  );

  const grouped = filtered.reduce<Record<string, CommandItem[]>>((acc, item) => {
    const group = item.group || 'General';
    if (!acc[group]) acc[group] = [];
    acc[group].push(item);
    return acc;
  }, {});

  const flatFiltered = Object.values(grouped).flat();

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setSelectedIndex(i => Math.min(i + 1, flatFiltered.length - 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setSelectedIndex(i => Math.max(i - 1, 0));
    } else if (e.key === 'Enter' && flatFiltered[selectedIndex]) {
      flatFiltered[selectedIndex].onSelect?.();
      setOpen(false);
    }
  };

  const handleOverlayClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) setOpen(false);
  };

  if (!isOpen) return null;

  return ReactDOM.createPortal(
    <div
      className={`ctp-command-overlay ${className}`}
      onClick={handleOverlayClick}
      role="dialog"
      aria-modal="true"
      aria-label="Command palette"
    >
      <div className="ctp-command">
        <div className="ctp-command__input-wrapper">
          <svg className="ctp-command__search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <circle cx="11" cy="11" r="8" />
            <line x1="21" y1="21" x2="16.65" y2="16.65" />
          </svg>
          <input
            ref={inputRef}
            className="ctp-command__input"
            placeholder={placeholder}
            value={query}
            onChange={e => { setQuery(e.target.value); setSelectedIndex(0); }}
            onKeyDown={handleKeyDown}
            role="combobox"
            aria-expanded={isOpen}
            aria-activedescendant={flatFiltered[selectedIndex] ? `ctp-cmd-item-${flatFiltered[selectedIndex].id}` : undefined}
            aria-controls="ctp-command-list"
            aria-autocomplete="list"
          />
        </div>
        <div ref={listRef} className="ctp-command__list" id="ctp-command-list" role="listbox">
          {flatFiltered.length === 0 ? (
            <div className="ctp-command__empty">{emptyMessage}</div>
          ) : (
            Object.entries(grouped).map(([group, groupItems]) => (
              <div key={group}>
                <div className="ctp-command__group-label">{group}</div>
                {groupItems.map((item, i) => {
                  const flatIndex = flatFiltered.indexOf(item);
                  return (
                    <div
                      key={item.id}
                      id={`ctp-cmd-item-${item.id}`}
                      role="option"
                      aria-selected={flatIndex === selectedIndex}
                      className={`ctp-command__item${flatIndex === selectedIndex ? ' ctp-command__item--selected' : ''}`}
                      onClick={() => { item.onSelect?.(); setOpen(false); }}
                      onMouseEnter={() => setSelectedIndex(flatIndex)}
                    >
                      {item.icon && <span className="ctp-command__item-icon">{item.icon}</span>}
                      <span className="ctp-command__item-label">{item.label}</span>
                      {item.shortcut && <span className="ctp-command__item-shortcut">{item.shortcut}</span>}
                    </div>
                  );
                })}
              </div>
            ))
          )}
        </div>
      </div>
    </div>,
    document.body
  );
};

Command.displayName = 'Command';

// packages/angular/src/command.component.ts
import { Component, input, output, signal, computed, effect, HostListener, ViewChild, ElementRef } from '@angular/core';

export interface CommandItem {
  id: string;
  label: string;
  group?: string;
  shortcut?: string;
  onSelect?: () => void;
}

@Component({
  selector: 'ctp-command',
  standalone: true,
  template: `
    @if (isOpen()) {
      <div class="ctp-command-overlay" (click)="onOverlayClick($event)" role="dialog" aria-modal="true" aria-label="Command palette">
        <div class="ctp-command">
          <div class="ctp-command__input-wrapper">
            <svg class="ctp-command__search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>
            </svg>
            <input
              #inputEl
              class="ctp-command__input"
              [placeholder]="placeholder()"
              (input)="onInput($event)"
              (keydown)="onKeyDown($event)"
            />
          </div>
          <div class="ctp-command__list">
            @if (flatFiltered().length === 0) {
              <div class="ctp-command__empty">{{ emptyMessage() }}</div>
            } @else {
              @for (group of groupKeys(); track group) {
                <div>
                  <div class="ctp-command__group-label">{{ group }}</div>
                  @for (item of grouped()[group]; track item.id) {
                    <div
                      [class]="'ctp-command__item' + (flatFiltered().indexOf(item) === selectedIndex() ? ' ctp-command__item--selected' : '')"
                      (click)="selectItem(item)"
                      (mouseenter)="selectedIndex.set(flatFiltered().indexOf(item))"
                    >
                      <span class="ctp-command__item-label">{{ item.label }}</span>
                      @if (item.shortcut) {
                        <span class="ctp-command__item-shortcut">{{ item.shortcut }}</span>
                      }
                    </div>
                  }
                </div>
              }
            }
          </div>
        </div>
      </div>
    }
  `
})
export class CommandComponent {
  items = input<CommandItem[]>([]);
  open = input<boolean>(false);
  placeholder = input<string>('Search commands...');
  emptyMessage = input<string>('No results found.');

  openChange = output<boolean>();

  @ViewChild('inputEl') inputEl!: ElementRef<HTMLInputElement>;

  query = signal('');
  selectedIndex = signal(0);

  isOpen = signal(false);

  private internalOpen = false;

  constructor() {
    effect(() => {
      const controlled = this.open();
      if (this.internalOpen !== controlled) {
        this.internalOpen = controlled;
        this.isOpen.set(controlled);
        if (controlled) {
          this.query.set('');
          this.selectedIndex.set(0);
          setTimeout(() => this.inputEl?.nativeElement?.focus(), 50);
        }
      }
    });
  }

  filtered = computed(() => {
    const q = this.query().toLowerCase();
    return this.items().filter(item => item.label.toLowerCase().includes(q));
  });

  grouped = computed(() => {
    const groups: Record<string, CommandItem[]> = {};
    for (const item of this.filtered()) {
      const g = item.group || 'General';
      if (!groups[g]) groups[g] = [];
      groups[g].push(item);
    }
    return groups;
  });

  groupKeys = computed(() => Object.keys(this.grouped()));
  flatFiltered = computed(() => this.filtered());

  @HostListener('window:keydown', ['$event'])
  onWindowKeyDown(e: KeyboardEvent): void {
    if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
      e.preventDefault();
      this.toggle();
    }
    if (e.key === 'Escape' && this.isOpen()) {
      this.close();
    }
  }

  toggle(): void {
    const next = !this.isOpen();
    this.internalOpen = next;
    this.isOpen.set(next);
    this.openChange.emit(next);
    if (next) {
      this.query.set('');
      this.selectedIndex.set(0);
    }
  }

  close(): void {
    this.internalOpen = false;
    this.isOpen.set(false);
    this.openChange.emit(false);
  }

  onInput(e: Event): void {
    this.query.set((e.target as HTMLInputElement).value);
    this.selectedIndex.set(0);
  }

  onKeyDown(e: KeyboardEvent): void {
    const flat = this.flatFiltered();
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      this.selectedIndex.update(i => Math.min(i + 1, flat.length - 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      this.selectedIndex.update(i => Math.max(i - 1, 0));
    } else if (e.key === 'Enter' && flat[this.selectedIndex()]) {
      flat[this.selectedIndex()].onSelect?.();
      this.close();
    }
  }

  selectItem(item: CommandItem): void {
    item.onSelect?.();
    this.close();
  }

  onOverlayClick(e: MouseEvent): void {
    if ((e.target as HTMLElement).classList.contains('ctp-command-overlay')) {
      this.close();
    }
  }
}
