// packages/vue/src/Grid.vue
<template>
  <div :class="gridClass">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

type GridGap = 0 | 1 | 2 | 3 | 4 | 5;
type GridAlign = 'start' | 'center' | 'end' | 'space-between' | 'space-around';
type GridValign = 'start' | 'center' | 'end';

interface Props {
  mobile?: boolean;
  multiline?: boolean;
  gap?: GridGap;
  align?: GridAlign;
  valign?: GridValign;
}

const props = withDefaults(defineProps<Props>(), {
  mobile: false,
  multiline: true,
  gap: 3,
});

const gridClass = computed(() => {
  return [
    'ctp-grid',
    props.mobile ? 'ctp-grid-mobile' : '',
    props.multiline ? 'ctp-grid-multiline' : '',
    `ctp-grid-gap-${props.gap}`,
    props.align ? `ctp-grid-align-${props.align}` : '',
    props.valign ? `ctp-grid-valign-${props.valign}` : '',
  ];
});
</script>

// packages/angular/src/grid.component.ts
import { Component, input, computed } from '@angular/core';

export type GridGap = 0 | 1 | 2 | 3 | 4 | 5;
export type GridAlign = 'start' | 'center' | 'end' | 'space-between' | 'space-around';
export type GridValign = 'start' | 'center' | 'end';
export type GridColSpan = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
export type GridOffset = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;

@Component({
  selector: 'ctp-grid',
  standalone: true,
  template: '<div [class]="gridClass()"><ng-content></ng-content></div>'
})
export class GridComponent {
  mobile = input<boolean>(false);
  multiline = input<boolean>(true);
  gap = input<GridGap>(3);
  align = input<GridAlign | undefined>(undefined);
  valign = input<GridValign | undefined>(undefined);

  protected gridClass = computed(() => {
    return [
      'ctp-grid',
      this.mobile() ? 'ctp-grid-mobile' : '',
      this.multiline() ? 'ctp-grid-multiline' : '',
      `ctp-grid-gap-${this.gap()}`,
      this.align() ? `ctp-grid-align-${this.align()}` : '',
      this.valign() ? `ctp-grid-valign-${this.valign()}` : '',
    ].filter(Boolean).join(' ');
  });
}

@Component({
  selector: 'ctp-grid-col',
  standalone: true,
  template: '<div [class]="colClass()"><ng-content></ng-content></div>'
})
export class GridColComponent {
  span = input<GridColSpan>(12);
  offset = input<GridOffset | undefined>(undefined);

  protected colClass = computed(() => {
    return [
      'ctp-grid-col',
      `ctp-grid-col-${this.span()}`,
      this.offset() ? `ctp-grid-col-offset-${this.offset()}` : '',
    ].filter(Boolean).join(' ');
  });
}
