// packages/vue/src/HoverCard.vue
<template>
  <div ref="hcEl" style="display:contents">
    <span
      class="ctp-hover-card__trigger"
      ref="triggerEl"
      @mouseenter="onMouseEnter"
      @mouseleave="onMouseLeave"
      @focusin="onFocus"
      @focusout="onBlur"
    >
      <slot name="trigger" />
    </span>
    <Teleport to="body">
      <div
        v-if="isVisible"
        ref="floatingEl"
        :class="['ctp-hover-card', `ctp-hover-card--placement-${actualPlacement}`]"
        :style="{ position: 'fixed', top: top + 'px', left: left + 'px', zIndex: 1100 }"
        @mouseenter="onCardEnter"
        @mouseleave="onCardLeave"
      >
        <div class="ctp-hover-card__arrow" />
        <slot />
      </div>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

type HoverCardPlacement = 'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end' | 'right' | 'right-start' | 'right-end';

interface Props {
  placement?: HoverCardPlacement;
  offset?: number;
  openDelay?: number;
  closeDelay?: number;
}

const props = withDefaults(defineProps<Props>(), {
  placement: 'bottom',
  offset: 8,
  openDelay: 400,
  closeDelay: 300,
});

const isVisible = ref(false);
const top = ref(0);
const left = ref(0);
const actualPlacement = ref<HoverCardPlacement>('bottom');
const hcEl = ref<HTMLElement>();
const triggerEl = ref<HTMLElement>();
const floatingEl = ref<HTMLElement>();
let timeoutId: ReturnType<typeof setTimeout> | null = null;

function updatePosition() {
  if (!triggerEl.value) return;
  const rect = triggerEl.value.getBoundingClientRect();
  actualPlacement.value = props.placement;
  top.value = rect.bottom + props.offset;
  left.value = rect.left;
}

function onMouseEnter() {
  if (timeoutId) clearTimeout(timeoutId);
  timeoutId = setTimeout(() => {
    isVisible.value = true;
    updatePosition();
  }, props.openDelay);
}

function onMouseLeave() {
  if (timeoutId) clearTimeout(timeoutId);
  timeoutId = setTimeout(() => {
    isVisible.value = false;
  }, props.closeDelay);
}

function onFocus() {
  if (timeoutId) clearTimeout(timeoutId);
  isVisible.value = true;
  updatePosition();
}

function onBlur() {
  if (timeoutId) clearTimeout(timeoutId);
  isVisible.value = false;
}

function onCardEnter() {
  if (timeoutId) clearTimeout(timeoutId);
}

function onCardLeave() {
  if (timeoutId) clearTimeout(timeoutId);
  timeoutId = setTimeout(() => {
    isVisible.value = false;
  }, props.closeDelay);
}
</script>

// packages/angular/src/hover-card.component.ts
import { Component, input, ElementRef, HostListener, inject } from '@angular/core';

type HoverCardPlacement = 'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end' | 'right' | 'right-start' | 'right-end';

@Component({
  selector: 'ctp-hover-card',
  standalone: true,
  template: `
    <span class="ctp-hover-card__trigger" #triggerRef
      (mouseenter)="onMouseEnter()" (mouseleave)="onMouseLeave()"
      (focusin)="onFocus()" (focusout)="onBlur()"
    >
      <ng-content select="[ctpHoverCardTrigger]" />
    </span>
    @if (isVisible) {
      <div
        #cardRef
        [class]="'ctp-hover-card ctp-hover-card--placement-' + actualPlacement"
        [style.position]="'fixed'"
        [style.zIndex]="'1100'"
        [style.top.px]="top"
        [style.left.px]="left"
        (mouseenter)="onCardEnter()"
        (mouseleave)="onCardLeave()"
      >
        <div class="ctp-hover-card__arrow"></div>
        <ng-content />
      </div>
    }
  `,
})
export class HoverCardComponent {
  placement = input<HoverCardPlacement>('bottom');
  offset = input<number>(8);
  openDelay = input<number>(400);
  closeDelay = input<number>(300);

  isVisible = false;
  top = 0;
  left = 0;
  actualPlacement: HoverCardPlacement = 'bottom';
  private timeoutId: any = null;
  private el = inject(ElementRef);

  onMouseEnter(): void {
    clearTimeout(this.timeoutId);
    this.timeoutId = setTimeout(() => {
      this.isVisible = true;
      this.updatePosition();
    }, this.openDelay());
  }

  onMouseLeave(): void {
    clearTimeout(this.timeoutId);
    this.timeoutId = setTimeout(() => {
      this.isVisible = false;
    }, this.closeDelay());
  }

  onFocus(): void {
    clearTimeout(this.timeoutId);
    this.isVisible = true;
    this.updatePosition();
  }

  onBlur(): void {
    clearTimeout(this.timeoutId);
    this.isVisible = false;
  }

  onCardEnter(): void {
    clearTimeout(this.timeoutId);
  }

  onCardLeave(): void {
    clearTimeout(this.timeoutId);
    this.timeoutId = setTimeout(() => {
      this.isVisible = false;
    }, this.closeDelay());
  }

  private updatePosition(): void {
    const nativeEl = this.el.nativeElement as HTMLElement;
    const trigger = nativeEl.querySelector('[ctpHoverCardTrigger]') as HTMLElement;
    const card = nativeEl.querySelector('.ctp-hover-card') as HTMLElement;
    if (!trigger || !card) return;

    const triggerRect = trigger.getBoundingClientRect();
    const offset = this.offset();

    this.actualPlacement = this.placement();
    this.top = triggerRect.bottom + offset;
    this.left = triggerRect.left;
  }
}
