// packages/react/src/Stepper.tsx
import React from 'react';
import { ButtonColor } from './Button';

export interface StepItem {
  label: string;
  description?: string;
  icon?: React.ReactNode;
}

export type StepperOrientation = 'horizontal' | 'vertical';
export type StepperVariant = 'default' | 'dots' | 'icon' | 'labeled-icon';

export interface StepperProps {
  steps: StepItem[];
  currentStep: number;
  orientation?: StepperOrientation;
  variant?: StepperVariant;
  color?: ButtonColor;
  className?: string;
}

const CheckIcon = () => (
  <svg viewBox="0 0 24 24" fill="currentColor">
    <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" />
  </svg>
);

export const Stepper: React.FC<StepperProps> = ({
  steps,
  currentStep,
  orientation = 'horizontal',
  variant = 'default',
  color = 'mauve',
  className = '',
}) => {
  const totalSteps = steps.length;
  const segments = Math.max(1, totalSteps - 1);
  const progressPercent = Math.min(100, Math.max(0, (currentStep / segments) * 100));

  const wrapperClassNames = [
    'ctp-stepper-wrapper',
    `ctp-stepper--${orientation}`,
    `ctp-stepper--${variant}`,
    `ctp-stepper--${color}`,
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const cssStyle = {
    '--ctp-total-steps': totalSteps,
    '--ctp-stepper-progress': `${progressPercent}%`,
  } as React.CSSProperties;

  return (
    <div className={wrapperClassNames} style={cssStyle}>
      {/* Background line track */}
      <div className="ctp-stepper__track">
        <div className="ctp-stepper__track-active" />
      </div>

      {/* Render Steps */}
      {steps.map((step, index) => {
        let status: 'completed' | 'active' | 'upcoming' = 'upcoming';
        if (index < currentStep) status = 'completed';
        else if (index === currentStep) status = 'active';

        const stepClassNames = [
          'ctp-stepper__step',
          `ctp-stepper__step--${status}`,
        ].join(' ');

        // Compute what to render inside the node circle
        let nodeContent: React.ReactNode = null;
        if (variant !== 'dots') {
          if (status === 'completed') {
            nodeContent = <CheckIcon />;
          } else if ((variant === 'icon' || variant === 'labeled-icon') && step.icon) {
            nodeContent = step.icon;
          } else {
            nodeContent = index + 1;
          }
        }

        return (
          <div key={index} className={stepClassNames}>
            {/* Step node icon / dot / number */}
            <div className="ctp-stepper__node">
              {nodeContent}
            </div>

            {/* Vertical track segment inside step item for vertical layout styling */}
            {orientation === 'vertical' && index < totalSteps - 1 && (
              <div className="ctp-stepper__track">
                <div 
                  className="ctp-stepper__track-active" 
                  style={{ 
                    height: index < currentStep ? '100%' : index === currentStep ? '50%' : '0%' 
                  }} 
                />
              </div>
            )}

            {/* Labels (skip rendering labels on horizontal if dot variant is active) */}
            {!(variant === 'dots' && orientation === 'horizontal') && (
              <div className="ctp-stepper__label-group">
                <h4 className="ctp-stepper__title">{step.label}</h4>
                {step.description && (
                  <p className="ctp-stepper__description">{step.description}</p>
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
};

Stepper.displayName = 'Stepper';

// packages/angular/src/stepper.component.ts
import { Component, input, computed } from '@angular/core';

type ButtonColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';

export interface StepItem {
  label: string;
  description?: string;
  icon?: string;
}

@Component({
  selector: 'ctp-stepper',
  standalone: true,
  template: `
    <div [class]="wrapperClass()" [style]="cssStyle()">
      <!-- Background line track -->
      <div class="ctp-stepper__track">
        <div class="ctp-stepper__track-active"></div>
      </div>

      <!-- Steps -->
      @for (step of steps(); track $index) {
        <div [class]="getStepClass($index)">
          <!-- Step node icon / dot / number -->
          <div class="ctp-stepper__node">
            @if (variant() !== 'dots') {
              @if ($index < currentStep()) {
                <!-- Completed check icon -->
                <svg viewBox="0 0 24 24" fill="currentColor" style="width: 1.1em; height: 1.1em">
                  <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" />
                </svg>
              } @else if ((variant() === 'icon' || variant() === 'labeled-icon') && step.icon) {
                <span>{{ step.icon }}</span>
              } @else {
                <span>{{ $index + 1 }}</span>
              }
            }
          </div>

          <!-- Vertical track segment inside step item for vertical layout styling -->
          @if (orientation() === 'vertical' && $index < steps().length - 1) {
            <div class="ctp-stepper__track">
              <div 
                class="ctp-stepper__track-active"
                [style.height]="$index < currentStep() ? '100%' : $index === currentStep() ? '50%' : '0%'"
              ></div>
            </div>
          }

          <!-- Labels -->
          @if (!(variant() === 'dots' && orientation() === 'horizontal')) {
            <div class="ctp-stepper__label-group">
              <h4 class="ctp-stepper__title">{{ step.label }}</h4>
              @if (step.description) {
                <p class="ctp-stepper__description">{{ step.description }}</p>
              }
            </div>
          }
        </div>
      }
    </div>
  `
})
export class StepperComponent {
  steps = input<StepItem[]>([]);
  currentStep = input<number>(0);
  orientation = input<'horizontal' | 'vertical'>('horizontal');
  variant = input<'default' | 'dots' | 'icon' | 'labeled-icon'>('default');
  color = input<ButtonColor>('mauve');

  segments = computed(() => Math.max(1, this.steps().length - 1));

  progressPercent = computed(() => {
    return Math.min(100, Math.max(0, (this.currentStep() / this.segments()) * 100));
  });

  wrapperClass = computed(() => {
    return [
      'ctp-stepper-wrapper',
      `ctp-stepper--${this.orientation()}`,
      `ctp-stepper--${this.variant()}`,
      `ctp-stepper--${this.color()}`,
    ].join(' ');
  });

  cssStyle = computed(() => {
    return {
      '--ctp-total-steps': String(this.steps().length),
      '--ctp-stepper-progress': `${this.progressPercent()}%`,
    };
  });

  getStepClass(index: number): string {
    let status = 'upcoming';
    if (index < this.currentStep()) {
      status = 'completed';
    } else if (index === this.currentStep()) {
      status = 'active';
    }
    return `ctp-stepper__step ctp-stepper__step--${status}`;
  }
}
