// packages/vue/src/Tooltip.vue
<template>
  <div
    style="position:relative;display:inline-flex"
    @mouseenter="onMouseEnter"
    @mouseleave="onMouseLeave"
    @focusin="onFocus"
    @focusout="onBlur"
  >
    <slot />
    <Teleport to="body" v-if="isVisible">
      <div
        :class="tooltipClass"
        style="position:fixed;z-index:1100"
        role="tooltip"
      >
        <div class="ctp-tooltip__content">{{ content }}</div>
        <div class="ctp-tooltip__arrow"></div>
      </div>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';

type TooltipPlacement = 'top' | 'bottom' | 'left' | 'right';

interface Props {
  content: string;
  placement?: TooltipPlacement;
  color?: string;
  delay?: number;
}

const props = withDefaults(defineProps<Props>(), {
  placement: 'top',
  color: 'dark',
  delay: 200,
});

const isVisible = ref(false);
let timeoutId: ReturnType<typeof setTimeout> | null = null;

const tooltipClass = computed(() => {
  const colorClass = props.color === 'dark' || props.color === 'light'
    ? `ctp-tooltip--preset-${props.color}`
    : `ctp-tooltip--${props.color}`;
  return [
    'ctp-tooltip',
    `ctp-tooltip--placement-${props.placement}`,
    colorClass,
  ];
});

function onMouseEnter() {
  if (timeoutId) clearTimeout(timeoutId);
  timeoutId = setTimeout(() => { isVisible.value = true; }, props.delay);
}

function onMouseLeave() {
  if (timeoutId) clearTimeout(timeoutId);
  isVisible.value = false;
}

function onFocus() {
  if (timeoutId) clearTimeout(timeoutId);
  isVisible.value = true;
}

function onBlur() {
  if (timeoutId) clearTimeout(timeoutId);
  isVisible.value = false;
}
</script>

// packages/angular/src/tooltip.component.ts
import { Component, input, computed, HostListener, ElementRef } from '@angular/core';

export type TooltipPlacement = 'top' | 'bottom' | 'left' | 'right';

@Component({
  selector: '[ctp-tooltip]',
  standalone: true,
  template: `
    <ng-content></ng-content>
    @if (isVisible) {
      <div
        [class]="tooltipClass()"
        [style.position]="'fixed'"
        [style.zIndex]="'1100'"
        role="tooltip"
      >
        <div class="ctp-tooltip__content">{{ content() }}</div>
        <div class="ctp-tooltip__arrow"></div>
      </div>
    }
  `,
  host: {
    '[style.position]': '"relative"',
  }
})
export class TooltipDirective {
  content = input.required<string>();
  placement = input<TooltipPlacement>('top');
  color = input<string>('dark');
  delay = input<number>(200);

  isVisible = false;
  private timeoutId: any = null;

  constructor(private el: ElementRef) {}

  protected tooltipClass = computed(() => {
    const colorClass = this.color() === 'dark' || this.color() === 'light'
      ? `ctp-tooltip--preset-${this.color()}`
      : `ctp-tooltip--${this.color()}`;
    return [
      'ctp-tooltip',
      `ctp-tooltip--placement-${this.placement()}`,
      colorClass,
    ].filter(Boolean).join(' ');
  });

  @HostListener('mouseenter')
  onMouseEnter() {
    clearTimeout(this.timeoutId);
    this.timeoutId = setTimeout(() => {
      this.isVisible = true;
    }, this.delay());
  }

  @HostListener('mouseleave')
  onMouseLeave() {
    clearTimeout(this.timeoutId);
    this.isVisible = false;
  }

  @HostListener('focusin')
  onFocus() {
    clearTimeout(this.timeoutId);
    this.isVisible = true;
  }

  @HostListener('focusout')
  onBlur() {
    clearTimeout(this.timeoutId);
    this.isVisible = false;
  }
}
