// packages/vue/src/ButtonGroup.vue
<template>
  <div
    ref="containerRef"
    class="ctp-btn-group"
    :data-orientation="orientation"
    :data-variant="variant"
    :data-shape="shape"
    :data-state="[
      props.selectionMode === 'single' && pillReady ? 'pill-active' : '',
      props.selectionMode !== 'none' ? props.selectionMode : ''
    ].filter(Boolean).join(' ') || undefined"
    :role="selectionMode === 'single' ? 'radiogroup' : undefined"
    @keydown="handleKeyDown"
  >
    <div
      v-if="props.selectionMode === 'single'"
      class="ctp-btn-group-pill"
      :style="pillStyle"
    />
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed, provide, ref, onMounted, onUnmounted, watch, nextTick } from 'vue';

export type ButtonGroupVariant = 'filled' | 'outline' | 'ghost';
type ButtonGroupSelectionMode = 'none' | 'single' | 'multiple';

interface Props {
  orientation?: 'horizontal' | 'vertical';
  variant?: ButtonGroupVariant;
  shape?: 'square' | 'rounded' | 'pill';
  selectionMode?: ButtonGroupSelectionMode;
  modelValue?: any;
  disabled?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  orientation: 'horizontal',
  variant: 'filled',
  shape: 'rounded',
  selectionMode: 'none',
  disabled: false,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: any): void;
  (e: 'change', value: any): void;
}>();

const containerRef = ref<HTMLElement | null>(null);
const buttonElements = ref<Map<any, HTMLElement>>(new Map());

const pillStyle = ref({
  transform: 'translate(0px, 0px)',
  width: '0px',
  height: '0px',
  opacity: '0',
  pointerEvents: 'none',
});

const pillReady = ref(false);

const updatePill = () => {
  nextTick(() => {
    if (!containerRef.value || props.selectionMode !== 'single') {
      pillStyle.value = { ...pillStyle.value, opacity: '0', pointerEvents: 'none' };
      pillReady.value = false;
      return;
    }

    const activeEl = buttonElements.value.get(props.modelValue);
    if (!activeEl) {
      pillStyle.value = { ...pillStyle.value, opacity: '0', pointerEvents: 'none' };
      pillReady.value = false;
      return;
    }

    const containerRect = containerRef.value.getBoundingClientRect();
    const activeRect = activeEl.getBoundingClientRect();

    const left = activeRect.left - containerRect.left;
    const top = activeRect.top - containerRect.top;
    const width = activeRect.width;
    const height = activeRect.height;

    pillStyle.value = {
      transform: `translate(${left}px, ${top}px)`,
      width: `${width}px`,
      height: `${height}px`,
      opacity: '1',
      pointerEvents: 'none',
    };
    pillReady.value = true;
  });
};

watch(() => props.modelValue, updatePill);
watch(() => props.selectionMode, updatePill);

let resizeObserver: ResizeObserver | null = null;
onMounted(() => {
  updatePill();
  if (containerRef.value) {
    resizeObserver = new ResizeObserver(() => {
      updatePill();
    });
    resizeObserver.observe(containerRef.value);
  }
});

onUnmounted(() => {
  if (resizeObserver) {
    resizeObserver.disconnect();
  }
});

const registerButton = (value: any, element: HTMLElement) => {
  buttonElements.value.set(value, element);
  updatePill();
};

const unregisterButton = (value: any) => {
  buttonElements.value.delete(value);
  updatePill();
};

provide('buttonGroupSelectionMode', computed(() => props.selectionMode));
provide('buttonGroupValue', computed(() => props.modelValue));
provide('buttonGroupDisabled', computed(() => props.disabled));
provide('registerButton', registerButton);
provide('unregisterButton', unregisterButton);

provide('buttonGroupSelect', (btnValue: any) => {
  if (props.selectionMode === 'none') return;

  if (props.selectionMode === 'single') {
    emit('update:modelValue', btnValue);
    emit('change', btnValue);
  } else if (props.selectionMode === 'multiple') {
    const currentValues = Array.isArray(props.modelValue) ? props.modelValue : [];
    let nextValue;
    if (currentValues.includes(btnValue)) {
      nextValue = currentValues.filter((v: any) => v !== btnValue);
    } else {
      nextValue = [...currentValues, btnValue];
    }
    emit('update:modelValue', nextValue);
    emit('change', nextValue);
  }
});

const handleKeyDown = (e: KeyboardEvent) => {
  if (props.selectionMode !== 'single') return;

  const keys = Array.from(buttonElements.value.keys());
  const currentIndex = keys.indexOf(props.modelValue);
  if (currentIndex === -1) return;

  let nextIndex = currentIndex;
  if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
    nextIndex = (currentIndex + 1) % keys.length;
    e.preventDefault();
  } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
    nextIndex = (currentIndex - 1 + keys.length) % keys.length;
    e.preventDefault();
  }

  if (nextIndex !== currentIndex) {
    const nextValue = keys[nextIndex];
    emit('update:modelValue', nextValue);
    emit('change', nextValue);
    nextTick(() => {
      const nextEl = buttonElements.value.get(nextValue);
      nextEl?.focus();
    });
  }
};

</script>

// packages/react/src/ButtonGroup.tsx
import React, { createContext, useContext, useEffect, useRef, useState } from 'react';
import { Button, ButtonProps, ButtonShape } from './Button';
import { usePrefix } from './PrefixContext';
import { cn, cnEl } from './cn';

export type ButtonGroupOrientation = 'horizontal' | 'vertical';
export type ButtonGroupVariant = 'filled' | 'outline' | 'ghost';
export type ButtonGroupSelectionMode = 'none' | 'single' | 'multiple';

export interface ButtonGroupProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange'> {
  orientation?: ButtonGroupOrientation;
  variant?: ButtonGroupVariant;
  shape?: ButtonShape;
  selectionMode?: ButtonGroupSelectionMode;
  value?: any;
  onChange?: (value: any) => void;
  className?: string;
  disabled?: boolean;
}

interface ButtonGroupContextProps {
  selectionMode: ButtonGroupSelectionMode;
  value: any;
  onChange: (btnValue: any) => void;
  disabled?: boolean;
  registerButton: (val: any, element: HTMLButtonElement) => () => void;
}

const ButtonGroupContext = createContext<ButtonGroupContextProps | null>(null);

export const ButtonGroup = React.forwardRef<HTMLDivElement, ButtonGroupProps>(
  (
    {
      orientation = 'horizontal',
      variant = 'filled',
      shape = 'rounded',
      selectionMode = 'none',
      value,
      onChange,
      className = '',
      children,
      disabled = false,
      ...props
    },
    ref
  ) => {
    const prefix = usePrefix();
    const containerRef = useRef<HTMLDivElement | null>(null);
    const [pillStyle, setPillStyle] = useState<React.CSSProperties>({
      opacity: 0,
      pointerEvents: 'none' as const,
    });
    const [pillReady, setPillReady] = useState(false);
    
    // Track references of option buttons to measure their dimensions
    const buttonElementsMap = useRef<Map<any, HTMLButtonElement>>(new Map());

    const registerButton = (val: any, element: HTMLButtonElement) => {
      buttonElementsMap.current.set(val, element);
      updatePillPosition();
      return () => {
        buttonElementsMap.current.delete(val);
        updatePillPosition();
      };
    };

    const updatePillPosition = () => {
      if (!containerRef.current || selectionMode !== 'single') {
        setPillStyle({ opacity: 0, pointerEvents: 'none' as const });
        setPillReady(false);
        return;
      }

      const activeElement = buttonElementsMap.current.get(value);
      if (!activeElement) {
        setPillStyle({ opacity: 0, pointerEvents: 'none' as const });
        setPillReady(false);
        return;
      }

      const containerRect = containerRef.current.getBoundingClientRect();
      const activeRect = activeElement.getBoundingClientRect();

      const left = activeRect.left - containerRect.left;
      const top = activeRect.top - containerRect.top;
      const width = activeRect.width;
      const height = activeRect.height;

      setPillStyle({
        transform: `translate(${left}px, ${top}px)`,
        width: `${width}px`,
        height: `${height}px`,
      });
      setPillReady(true);
    };

    // Recalculate on value change
    useEffect(() => {
      updatePillPosition();
    }, [value, selectionMode, variant]);

    // Recalculate on resize
    useEffect(() => {
      if (!containerRef.current) return;
      const observer = new ResizeObserver(() => {
        updatePillPosition();
      });
      observer.observe(containerRef.current);
      return () => observer.disconnect();
    }, [value, selectionMode]);

    const handleButtonClick = (btnValue: any) => {
      if (selectionMode === 'none' || !onChange || btnValue === undefined) {
        return;
      }

      if (selectionMode === 'single') {
        onChange(btnValue);
      } else if (selectionMode === 'multiple') {
        const currentValues = Array.isArray(value) ? value : [];
        if (currentValues.includes(btnValue)) {
          onChange(currentValues.filter((val) => val !== btnValue));
        } else {
          onChange([...currentValues, btnValue]);
        }
      }
    };

    // Keyboard Arrow Navigation for Radio Group (Selection mode single)
    const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
      if (selectionMode !== 'single') return;

      const keys = Array.from(buttonElementsMap.current.keys());
      const currentIndex = keys.indexOf(value);
      if (currentIndex === -1) return;

      let nextIndex = currentIndex;
      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
        nextIndex = (currentIndex + 1) % keys.length;
        e.preventDefault();
      } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
        nextIndex = (currentIndex - 1 + keys.length) % keys.length;
        e.preventDefault();
      }

      if (nextIndex !== currentIndex) {
        const nextValue = keys[nextIndex];
        handleButtonClick(nextValue);
        // Focus the next active button
        setTimeout(() => {
          const btnEl = buttonElementsMap.current.get(nextValue);
          btnEl?.focus();
        }, 0);
      }
    };

    const classNames = [
      cn(prefix, 'btn-group', [orientation, variant, shape, (selectionMode === 'single' && pillReady) ? 'pill-active' : undefined, selectionMode !== 'none' ? selectionMode : undefined]),
      className,
    ]
      .filter(Boolean)
      .join(' ');

    const setRef = (node: HTMLDivElement | null) => {
      containerRef.current = node;
      if (typeof ref === 'function') {
        ref(node);
      } else if (ref) {
        ref.current = node;
      }
    };

    return (
      <ButtonGroupContext.Provider
        value={{
          selectionMode,
          value,
          onChange: handleButtonClick,
          disabled,
          registerButton,
        }}
      >
        <div
          ref={setRef}
          className={classNames}
          role={selectionMode === 'single' ? 'radiogroup' : undefined}
          onKeyDown={handleKeyDown}
          {...props}
        >
          {selectionMode === 'single' && (
            <div className={cnEl(prefix, 'btn-group', 'pill')} style={pillStyle} />
          )}
          {children}
        </div>
      </ButtonGroupContext.Provider>
    );
  }
);

ButtonGroup.displayName = 'ButtonGroup';

export interface ButtonGroupItemProps extends ButtonProps {
  value: any;
}

export const ButtonGroupItem = React.forwardRef<HTMLButtonElement, ButtonGroupItemProps>(
  ({ value: itemValue, className = '', children, disabled, onClick, ...props }, ref) => {
    const prefix = usePrefix();
    const context = useContext(ButtonGroupContext);
    const itemRef = useRef<HTMLButtonElement | null>(null);

    const isGroupItem = !!context;
    const selectionMode = context?.selectionMode ?? 'none';
    const groupValue = context?.value;
    const isGroupDisabled = context?.disabled;

    let isActive = false;
    if (selectionMode === 'single') {
      isActive = groupValue === itemValue;
    } else if (selectionMode === 'multiple') {
      isActive = Array.isArray(groupValue) && groupValue.includes(itemValue);
    }

    useEffect(() => {
      if (context && itemRef.current) {
        return context.registerButton(itemValue, itemRef.current);
      }
    }, [context, itemValue]);

    const setMergedRef = (node: HTMLButtonElement | null) => {
      itemRef.current = node;
      if (typeof ref === 'function') {
        ref(node);
      } else if (ref) {
        ref.current = node;
      }
    };

    const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
      if (onClick) onClick(e);
      if (context) {
        context.onChange(itemValue);
      }
    };

    const finalDisabled = disabled || isGroupDisabled;

    const classNames = [
      isActive ? cn(prefix, 'btn', ['active']) : '',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <Button
        ref={setMergedRef}
        className={classNames}
        disabled={finalDisabled}
        role={selectionMode === 'single' ? 'radio' : undefined}
        aria-checked={selectionMode === 'single' ? isActive : undefined}
        tabIndex={selectionMode === 'single' ? (isActive ? 0 : -1) : 0}
        onClick={handleClick}
        {...props}
      >
        {children}
      </Button>
    );
  }
);

ButtonGroupItem.displayName = 'ButtonGroupItem';
