// packages/angular/src/button.component.ts
import {
  Component,
  input,
  computed,
  Optional,
  HostListener,
  ElementRef,
  AfterViewInit,
  OnDestroy,
  OnChanges,
  SimpleChanges
} from '@angular/core';
import { ButtonGroupComponent } from './button-group.component';

type ButtonVariant = 'filled' | 'tonal' | 'outline' | 'ghost';
type ButtonColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';
type ButtonSize = 'sm' | 'md' | 'lg';
type ButtonShape = 'square' | 'rounded' | 'pill';

@Component({
  selector: 'ctp-button',
  standalone: true,
  template: `
    <button
      [class]="buttonClass()"
      [disabled]="disabled() || isGroupDisabled() || isLoading()"
      [attr.role]="isGroupSingle() ? 'radio' : null"
      [attr.aria-checked]="isGroupSingle() ? isActive() : null"
      [attr.tabindex]="isGroupSingle() ? (isActive() ? 0 : -1) : 0"
    >
      <span class="ctp-btn__content">
        @if (isLoading()) {
          <span class="ctp-btn__spinner" aria-hidden="true"></span>
        }
        <span class="ctp-btn__icon-left" style="display: inline-flex; align-items: center">
          <ng-content select="[leftIcon]"></ng-content>
        </span>
        <ng-content></ng-content>
        <span class="ctp-btn__icon-right" style="display: inline-flex; align-items: center">
          <ng-content select="[rightIcon]"></ng-content>
        </span>
      </span>
    </button>
  `
})
export class ButtonComponent implements AfterViewInit, OnDestroy, OnChanges {
  variant = input<ButtonVariant>('filled');
  color = input<ButtonColor>('mauve');
  size = input<ButtonSize>('md');
  shape = input<ButtonShape>('rounded');
  isLoading = input<boolean>(false);
  disabled = input<boolean>(false);
  value = input<any>(null);

  constructor(
    @Optional() public buttonGroup: ButtonGroupComponent,
    private el: ElementRef
  ) {}

  @HostListener('click', ['$event'])
  onClick(event: MouseEvent) {
    if (this.buttonGroup && this.value() !== null) {
      this.buttonGroup.selectButton(this.value());
    }
  }

  isGroupSingle = computed(() => {
    return this.buttonGroup ? this.buttonGroup.selectionMode() === 'single' : false;
  });

  isGroupDisabled = computed(() => {
    return this.buttonGroup ? this.buttonGroup.disabled() : false;
  });

  isActive = computed(() => {
    if (this.buttonGroup && this.value() !== null) {
      return this.buttonGroup.isButtonActive(this.value());
    }
    return false;
  });

  buttonClass = computed(() => {
    return [
      'ctp-btn',
      `ctp-btn--${this.variant()}`,
      `ctp-btn--${this.color()}`,
      `ctp-btn--${this.size()}`,
      `ctp-btn--${this.shape()}`,
      this.isLoading() ? 'ctp-btn--loading' : '',
      this.isActive() ? 'ctp-btn--active' : '',
    ]
      .filter(Boolean)
      .join(' ');
  });

  ngAfterViewInit() {
    if (this.buttonGroup && this.value() !== null) {
      this.buttonGroup.registerButton(this.value(), this.el.nativeElement.querySelector('button'));
    }
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['value'] && this.buttonGroup) {
      const prev = changes['value'].previousValue;
      const curr = changes['value'].currentValue;
      if (prev !== null && prev !== undefined) {
        this.buttonGroup.unregisterButton(prev);
      }
      if (curr !== null && curr !== undefined) {
        this.buttonGroup.registerButton(curr, this.el.nativeElement.querySelector('button'));
      }
    }
  }

  ngOnDestroy() {
    if (this.buttonGroup && this.value() !== null) {
      this.buttonGroup.unregisterButton(this.value());
    }
  }
}

// packages/react/src/Button.tsx
import React from 'react';

export type ButtonVariant = 'filled' | 'tonal' | 'outline' | 'ghost';
export type ButtonColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';
export type ButtonSize = 'sm' | 'md' | 'lg';
export type ButtonShape = 'square' | 'rounded' | 'pill';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  color?: ButtonColor;
  size?: ButtonSize;
  shape?: ButtonShape;
  isLoading?: boolean;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
}

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      variant = 'filled',
      color = 'mauve',
      size = 'md',
      shape = 'rounded',
      isLoading = false,
      leftIcon,
      rightIcon,
      className = '',
      children,
      disabled,
      ...props
    },
    ref
  ) => {
    const classNames = [
      'ctp-btn',
      `ctp-btn--${variant}`,
      `ctp-btn--${color}`,
      `ctp-btn--${size}`,
      `ctp-btn--${shape}`,
      isLoading ? 'ctp-btn--loading' : '',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <button
        ref={ref}
        className={classNames}
        disabled={disabled || isLoading}
        {...props}
      >
        <span className="ctp-btn__content">
          {isLoading && <span className="ctp-btn__spinner" aria-hidden="true" />}
          {!isLoading && leftIcon && <span className="ctp-btn__icon-left" style={{ display: 'inline-flex', alignItems: 'center' }}>{leftIcon}</span>}
          {children}
          {!isLoading && rightIcon && <span className="ctp-btn__icon-right" style={{ display: 'inline-flex', alignItems: 'center' }}>{rightIcon}</span>}
        </span>
      </button>
    );
  }
);

Button.displayName = 'Button';
