// packages/vue/src/HoverCard.vue
<template>
  <div ref="hcEl" style="display:contents">
    <span
      class="ctp-hover-card__trigger"
      ref="triggerEl"
      @mouseenter="onMouseEnter"
      @mouseleave="onMouseLeave"
      @focusin="onFocus"
      @focusout="onBlur"
    >
      <slot name="trigger" />
    </span>
    <Teleport to="body">
      <div
        v-if="isVisible"
        ref="floatingEl"
        :class="['ctp-hover-card', `ctp-hover-card--placement-${actualPlacement}`]"
        :style="{ position: 'fixed', top: top + 'px', left: left + 'px', zIndex: 1100 }"
        @mouseenter="onCardEnter"
        @mouseleave="onCardLeave"
      >
        <div class="ctp-hover-card__arrow" />
        <slot />
      </div>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

type HoverCardPlacement = 'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end' | 'right' | 'right-start' | 'right-end';

interface Props {
  placement?: HoverCardPlacement;
  offset?: number;
  openDelay?: number;
  closeDelay?: number;
}

const props = withDefaults(defineProps<Props>(), {
  placement: 'bottom',
  offset: 8,
  openDelay: 400,
  closeDelay: 300,
});

const isVisible = ref(false);
const top = ref(0);
const left = ref(0);
const actualPlacement = ref<HoverCardPlacement>('bottom');
const hcEl = ref<HTMLElement>();
const triggerEl = ref<HTMLElement>();
const floatingEl = ref<HTMLElement>();
let timeoutId: ReturnType<typeof setTimeout> | null = null;

function updatePosition() {
  if (!triggerEl.value) return;
  const rect = triggerEl.value.getBoundingClientRect();
  actualPlacement.value = props.placement;
  top.value = rect.bottom + props.offset;
  left.value = rect.left;
}

function onMouseEnter() {
  if (timeoutId) clearTimeout(timeoutId);
  timeoutId = setTimeout(() => {
    isVisible.value = true;
    updatePosition();
  }, props.openDelay);
}

function onMouseLeave() {
  if (timeoutId) clearTimeout(timeoutId);
  timeoutId = setTimeout(() => {
    isVisible.value = false;
  }, props.closeDelay);
}

function onFocus() {
  if (timeoutId) clearTimeout(timeoutId);
  isVisible.value = true;
  updatePosition();
}

function onBlur() {
  if (timeoutId) clearTimeout(timeoutId);
  isVisible.value = false;
}

function onCardEnter() {
  if (timeoutId) clearTimeout(timeoutId);
}

function onCardLeave() {
  if (timeoutId) clearTimeout(timeoutId);
  timeoutId = setTimeout(() => {
    isVisible.value = false;
  }, props.closeDelay);
}
</script>

// packages/react/src/HoverCard.tsx
import React, { useState, useRef, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { usePortalPosition, type Placement } from './usePortalPosition';

export interface HoverCardProps {
  children: [React.ReactElement, React.ReactElement];
  placement?: Placement;
  offset?: number;
  openDelay?: number;
  closeDelay?: number;
  autoFlip?: boolean;
  className?: string;
}

export const HoverCard: React.FC<HoverCardProps> = ({
  children,
  placement = 'bottom',
  offset = 8,
  openDelay = 400,
  closeDelay = 300,
  autoFlip = true,
  className = '',
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const triggerRef = useRef<HTMLElement>(null);
  const floatingRef = useRef<HTMLDivElement>(null);
  const timeoutRef = useRef<ReturnType<typeof setTimeout>>();

  const { top, left, actualPlacement } = usePortalPosition(triggerRef, floatingRef, {
    isOpen,
    placement,
    offset,
    autoFlip,
  });

  const show = () => {
    clearTimeout(timeoutRef.current);
    timeoutRef.current = setTimeout(() => setIsOpen(true), openDelay);
  };

  const hide = () => {
    clearTimeout(timeoutRef.current);
    timeoutRef.current = setTimeout(() => setIsOpen(false), closeDelay);
  };

  useEffect(() => {
    return () => clearTimeout(timeoutRef.current);
  }, []);

  const [trigger, content] = React.Children.toArray(children) as [React.ReactElement, React.ReactElement];

  const triggerEl = React.isValidElement(trigger)
    ? React.cloneElement(trigger as React.ReactElement<any>, {
        ref: triggerRef,
        'aria-haspopup': 'dialog',
        'aria-expanded': isOpen,
        onMouseEnter: (e: React.MouseEvent) => {
          trigger.props.onMouseEnter?.(e);
          show();
        },
        onMouseLeave: (e: React.MouseEvent) => {
          trigger.props.onMouseLeave?.(e);
          hide();
        },
        onFocus: (e: React.FocusEvent) => {
          trigger.props.onFocus?.(e);
          show();
        },
        onBlur: (e: React.FocusEvent) => {
          trigger.props.onBlur?.(e);
          hide();
        },
      })
    : trigger;

  return (
    <>
      {triggerEl}
      {isOpen && ReactDOM.createPortal(
        <div
          ref={floatingRef}
          className={`ctp-hover-card ctp-hover-card--placement-${actualPlacement} ${className}`}
          style={{
            position: 'fixed',
            top: `${top}px`,
            left: `${left}px`,
            zIndex: 1100,
          }}
          onMouseEnter={() => clearTimeout(timeoutRef.current)}
          onMouseLeave={() => hide()}
        >
          <div className="ctp-hover-card__arrow" />
          {content}
        </div>,
        document.body
      )}
    </>
  );
};

HoverCard.displayName = 'HoverCard';
