// packages/vue/src/Overlay.vue
<template>
  <Teleport to="body">
    <div
      v-if="shouldRender"
      :class="['ctp-overlay', { 'ctp-overlay--open': isAnimatedIn }]"
      :style="{ zIndex: zIndex }"
      @click="handleOverlayClick"
      role="presentation"
    >
      <slot />
    </div>
  </Teleport>
</template>

<script lang="ts">
// Module-level count of open overlays for z-index stacking
let activeOverlayCount = 0;
</script>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted } from 'vue';

interface Props {
  isOpen: boolean;
  closeOnOverlayClick?: boolean;
  closeOnEsc?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  closeOnOverlayClick: true,
  closeOnEsc: true,
});

const emit = defineEmits<{
  (e: 'close'): void;
}>();

const shouldRender = ref(props.isOpen);
const isAnimatedIn = ref(false);
const zIndex = ref(1000);
let timeoutId: any = null;

watch(() => props.isOpen, (newVal) => {
  clearTimeout(timeoutId);
  if (newVal) {
    activeOverlayCount++;
    zIndex.value = 1000 + activeOverlayCount;
    shouldRender.value = true;
    document.body.style.overflow = 'hidden';
    timeoutId = setTimeout(() => {
      isAnimatedIn.value = true;
    }, 10);
  } else {
    isAnimatedIn.value = false;
    timeoutId = setTimeout(() => {
      shouldRender.value = false;
      if (activeOverlayCount > 0) {
        activeOverlayCount--;
      }
      if (activeOverlayCount === 0) {
        document.body.style.overflow = '';
      }
    }, 200);
  }
}, { immediate: true });

const handleOverlayClick = (e: MouseEvent) => {
  if (props.closeOnOverlayClick && e.target === e.currentTarget) {
    emit('close');
  }
};

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'Escape' && props.isOpen && props.closeOnEsc) {
    if (zIndex.value === 1000 + activeOverlayCount) {
      emit('close');
    }
  }
};

onMounted(() => {
  window.addEventListener('keydown', handleKeyDown);
});

onUnmounted(() => {
  window.removeEventListener('keydown', handleKeyDown);
  clearTimeout(timeoutId);
  if (props.isOpen) {
    if (activeOverlayCount > 0) {
      activeOverlayCount--;
    }
    if (activeOverlayCount === 0) {
      document.body.style.overflow = '';
    }
  }
});
</script>

// packages/react/src/Overlay.tsx
import React, { useEffect, useState } from 'react';
import ReactDOM from 'react-dom';

export interface OverlayProps {
  isOpen: boolean;
  onClose?: () => void;
  closeOnOverlayClick?: boolean;
  closeOnEsc?: boolean;
  children: React.ReactNode;
  className?: string;
}

// Module-level count of open overlays for z-index stacking
let activeOverlayCount = 0;

export const Overlay: React.FC<OverlayProps> = ({
  isOpen,
  onClose,
  closeOnOverlayClick = true,
  closeOnEsc = true,
  children,
  className = '',
}) => {
  const [shouldRender, setShouldRender] = useState(isOpen);
  const [isAnimatedIn, setIsAnimatedIn] = useState(false);
  const [zIndex, setZIndex] = useState(1000);

  useEffect(() => {
    let timeoutId: NodeJS.Timeout;

    if (isOpen) {
      activeOverlayCount++;
      setZIndex(1000 + activeOverlayCount);
      setShouldRender(true);

      // Wait a micro-frame to apply the CSS transition class
      timeoutId = setTimeout(() => {
        setIsAnimatedIn(true);
      }, 10);
    } else {
      setIsAnimatedIn(false);
      // Wait for CSS transition (200ms) to complete before unmounting
      timeoutId = setTimeout(() => {
        setShouldRender(false);
        if (activeOverlayCount > 0) {
          activeOverlayCount--;
        }
      }, 200);
    }

    return () => {
      clearTimeout(timeoutId);
    };
  }, [isOpen]);

  // Handle ESC key press
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && isOpen && onClose && closeOnEsc) {
        // Only close if this is the top-most overlay in the stack
        if (zIndex === 1000 + activeOverlayCount) {
          onClose();
        }
      }
    };

    if (isOpen) {
      window.addEventListener('keydown', handleKeyDown);
    }
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [isOpen, onClose, closeOnEsc, zIndex]);

  // Lock and unlock body scroll
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      // Small timeout to allow transition to finish
      const t = setTimeout(() => {
        if (activeOverlayCount === 0) {
          document.body.style.overflow = '';
        }
      }, 200);
      return () => clearTimeout(t);
    }
    return () => {
      if (activeOverlayCount === 0) {
        document.body.style.overflow = '';
      }
    };
  }, [isOpen]);

  // Cleanup overlay count on unmount
  useEffect(() => {
    return () => {
      if (isOpen) {
        if (activeOverlayCount > 0) {
          activeOverlayCount--;
        }
        if (activeOverlayCount === 0) {
          document.body.style.overflow = '';
        }
      }
    };
  }, []);

  const handleOverlayClick = (e: React.MouseEvent<HTMLDivElement>) => {
    if (closeOnOverlayClick && e.target === e.currentTarget && onClose) {
      onClose();
    }
  };

  if (!shouldRender) return null;

  const overlayElement = (
    <div
      className={`ctp-overlay ${isAnimatedIn ? 'ctp-overlay--open' : ''} ${className}`}
      onClick={handleOverlayClick}
      style={{ zIndex }}
      role="presentation"
    >
      {children}
    </div>
  );

  return ReactDOM.createPortal(overlayElement, document.body);
};
