// packages/vue/src/Popover.vue
<template>
  <div ref="popoverEl" style="display:contents">
    <span class="ctp-popover__trigger" ref="triggerEl" @click="toggle">
      <slot name="trigger" />
    </span>
    <Teleport to="body">
      <div
        v-if="isOpen"
        ref="floatingEl"
        :class="['ctp-popover', `ctp-popover--placement-${actualPlacement}`]"
        :style="{ position: 'fixed', top: top + 'px', left: left + 'px', zIndex: 1100 }"
      >
        <div class="ctp-popover__arrow" />
        <slot />
      </div>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

type PopoverPlacement = 'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end' | 'right' | 'right-start' | 'right-end';

interface Props {
  placement?: PopoverPlacement;
  offset?: number;
  open?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  placement: 'bottom',
  offset: 8,
});

const emit = defineEmits<{
  (e: 'update:open', val: boolean): void;
}>();

const isOpen = ref(false);
const top = ref(0);
const left = ref(0);
const actualPlacement = ref<PopoverPlacement>('bottom');
const popoverEl = ref<HTMLElement>();
const triggerEl = ref<HTMLElement>();
const floatingEl = ref<HTMLElement>();

function toggle() {
  isOpen.value = !isOpen.value;
  emit('update:open', isOpen.value);
  if (isOpen.value) updatePosition();
}

function updatePosition() {
  if (!triggerEl.value) return;
  const rect = triggerEl.value.getBoundingClientRect();
  actualPlacement.value = props.placement;
  top.value = rect.bottom + props.offset;
  left.value = rect.left;
}

function onClickOutside(e: MouseEvent) {
  if (!isOpen.value) return;
  const target = e.target as Node;
  if (popoverEl.value && !popoverEl.value.contains(target)) {
    isOpen.value = false;
    emit('update:open', false);
  }
}

function onEscape(e: KeyboardEvent) {
  if (e.key === 'Escape' && isOpen.value) {
    isOpen.value = false;
    emit('update:open', false);
  }
}

onMounted(() => {
  document.addEventListener('mousedown', onClickOutside);
  document.addEventListener('keydown', onEscape);
});
onUnmounted(() => {
  document.removeEventListener('mousedown', onClickOutside);
  document.removeEventListener('keydown', onEscape);
});
</script>

// packages/react/src/Popover.tsx
import React, { useState, useRef, useEffect, useCallback } from 'react';
import ReactDOM from 'react-dom';
import { usePortalPosition, type Placement } from './usePortalPosition';

export interface PopoverProps {
  children: [React.ReactElement, React.ReactElement];
  placement?: Placement;
  offset?: number;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  autoFlip?: boolean;
  className?: string;
}

export const Popover: React.FC<PopoverProps> = ({
  children,
  placement = 'bottom',
  offset = 8,
  open: controlledOpen,
  onOpenChange,
  autoFlip = true,
  className = '',
}) => {
  const [uncontrolledOpen, setUncontrolledOpen] = useState(false);
  const isControlled = controlledOpen !== undefined;
  const isOpen = isControlled ? controlledOpen : uncontrolledOpen;

  const triggerRef = useRef<HTMLElement>(null);
  const floatingRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLElement>(null);

  const setOpen = useCallback((open: boolean) => {
    if (!isControlled) setUncontrolledOpen(open);
    onOpenChange?.(open);
  }, [isControlled, onOpenChange]);

  const { top, left, actualPlacement } = usePortalPosition(triggerRef, floatingRef, {
    isOpen,
    placement,
    offset,
    autoFlip,
  });

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (
        isOpen &&
        floatingRef.current &&
        !floatingRef.current.contains(e.target as Node) &&
        triggerRef.current &&
        !triggerRef.current.contains(e.target as Node)
      ) {
        setOpen(false);
      }
    };

    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) setOpen(false);
    };

    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
      document.addEventListener('keydown', handleEscape);
    }
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
      document.removeEventListener('keydown', handleEscape);
    };
  }, [isOpen, setOpen]);

  const [trigger, content] = React.Children.toArray(children) as [React.ReactElement, React.ReactElement];

  useEffect(() => {
    if (isOpen && floatingRef.current) {
      const firstFocusable = floatingRef.current.querySelector<HTMLElement>(
        'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
      );
      firstFocusable?.focus();
    }
  }, [isOpen]);

  const triggerEl = React.isValidElement(trigger)
    ? React.cloneElement(trigger as React.ReactElement<any>, {
        ref: triggerRef,
        'aria-haspopup': 'dialog',
        'aria-expanded': isOpen,
        onClick: (e: React.MouseEvent) => {
          trigger.props.onClick?.(e);
          setOpen(!isOpen);
        },
      })
    : trigger;

  return (
    <>
      {triggerEl}
      {isOpen && ReactDOM.createPortal(
        <div
          ref={floatingRef}
          className={`ctp-popover ctp-popover--placement-${actualPlacement} ${className}`}
          style={{
            position: 'fixed',
            top: `${top}px`,
            left: `${left}px`,
            zIndex: 1100,
          }}
          role="dialog"
          aria-modal="true"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="ctp-popover__arrow" />
          {content}
        </div>,
        document.body
      )}
    </>
  );
};

Popover.displayName = 'Popover';
