// packages/vue/src/ScrollArea.vue
<template>
  <div class="ctp-scroll-area" :style="{ height }">
    <div ref="viewport" class="ctp-scroll-area__viewport" @scroll="updateThumbs">
      <slot />
    </div>
    <div
      v-if="showVertical"
      class="ctp-scroll-area__scrollbar ctp-scroll-area__scrollbar--vertical"
      :style="{ opacity: isDraggingV ? 1 : 0.6 }"
    >
      <div
        class="ctp-scroll-area__thumb"
        :style="{ height: thumbHeight + 'px', transform: `translateY(${thumbTop}px)` }"
        @mousedown.prevent="startDragV"
      />
    </div>
    <div
      v-if="showHorizontal"
      class="ctp-scroll-area__scrollbar ctp-scroll-area__scrollbar--horizontal"
      :style="{ opacity: isDraggingH ? 1 : 0.6 }"
    >
      <div
        class="ctp-scroll-area__thumb"
        :style="{ width: thumbWidth + 'px', transform: `translateX(${thumbLeft}px)` }"
        @mousedown.prevent="startDragH"
      />
    </div>
    <div v-if="showVertical && showHorizontal" class="ctp-scroll-area__corner" />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

interface Props {
  height?: string;
}

const props = withDefaults(defineProps<Props>(), {
  height: '100%',
});

const viewport = ref<HTMLElement>();
const showVertical = ref(false);
const showHorizontal = ref(false);
const thumbTop = ref(0);
const thumbLeft = ref(0);
const thumbHeight = ref(0);
const thumbWidth = ref(0);
const isDraggingV = ref(false);
const isDraggingH = ref(false);

function updateThumbs() {
  const vp = viewport.value;
  if (!vp) return;

  const { scrollTop, scrollLeft, scrollHeight, scrollWidth, clientHeight, clientWidth } = vp;

  showVertical.value = scrollHeight > clientHeight;
  showHorizontal.value = scrollWidth > clientWidth;

  if (scrollHeight > clientHeight) {
    thumbHeight.value = (clientHeight / scrollHeight) * clientHeight;
    thumbTop.value = (scrollTop / scrollHeight) * clientHeight;
  }
  if (scrollWidth > clientWidth) {
    thumbWidth.value = (clientWidth / scrollWidth) * clientWidth;
    thumbLeft.value = (scrollLeft / scrollWidth) * clientWidth;
  }
}

function startDragV(e: MouseEvent) {
  isDraggingV.value = true;
  const vp = viewport.value!;
  const startY = e.clientY;
  const startScrollTop = vp.scrollTop;

  function onMove(ev: MouseEvent) {
    const dy = ev.clientY - startY;
    const ratio = dy / (vp.clientHeight - thumbHeight.value);
    vp.scrollTop = startScrollTop + ratio * (vp.scrollHeight - vp.clientHeight);
  }

  function onUp() {
    isDraggingV.value = false;
    window.removeEventListener('mousemove', onMove);
    window.removeEventListener('mouseup', onUp);
  }

  window.addEventListener('mousemove', onMove);
  window.addEventListener('mouseup', onUp);
}

function startDragH(e: MouseEvent) {
  isDraggingH.value = true;
  const vp = viewport.value!;
  const startX = e.clientX;
  const startScrollLeft = vp.scrollLeft;

  function onMove(ev: MouseEvent) {
    const dx = ev.clientX - startX;
    const ratio = dx / (vp.clientWidth - thumbWidth.value);
    vp.scrollLeft = startScrollLeft + ratio * (vp.scrollWidth - vp.clientWidth);
  }

  function onUp() {
    isDraggingH.value = false;
    window.removeEventListener('mousemove', onMove);
    window.removeEventListener('mouseup', onUp);
  }

  window.addEventListener('mousemove', onMove);
  window.addEventListener('mouseup', onUp);
}

let ro: ResizeObserver;

onMounted(() => {
  if (viewport.value) {
    ro = new ResizeObserver(updateThumbs);
    ro.observe(viewport.value);
    updateThumbs();
  }
});

onUnmounted(() => {
  ro?.disconnect();
});
</script>

// packages/react/src/ScrollArea.tsx
import React, { useRef, useState, useEffect, useCallback } from 'react';

export interface ScrollAreaProps {
  children: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const ScrollArea: React.FC<ScrollAreaProps> = ({
  children,
  className = '',
  style,
}) => {
  const viewportRef = useRef<HTMLDivElement>(null);
  const verticalThumbRef = useRef<HTMLDivElement>(null);
  const horizontalThumbRef = useRef<HTMLDivElement>(null);
  const [showVertical, setShowVertical] = useState(false);
  const [showHorizontal, setShowHorizontal] = useState(false);
  const [thumbTop, setThumbTop] = useState(0);
  const [thumbLeft, setThumbLeft] = useState(0);
  const [thumbHeight, setThumbHeight] = useState(0);
  const [thumbWidth, setThumbWidth] = useState(0);
  const [isDragging, setIsDragging] = useState<'vertical' | 'horizontal' | null>(null);

  const updateThumbs = useCallback(() => {
    const viewport = viewportRef.current;
    if (!viewport) return;

    const { scrollTop, scrollLeft, scrollHeight, scrollWidth, clientHeight, clientWidth } = viewport;

    setShowVertical(scrollHeight > clientHeight);
    setShowHorizontal(scrollWidth > clientWidth);

    if (scrollHeight > clientHeight) {
      setThumbHeight((clientHeight / scrollHeight) * clientHeight);
      setThumbTop((scrollTop / scrollHeight) * clientHeight);
    }

    if (scrollWidth > clientWidth) {
      setThumbWidth((clientWidth / scrollWidth) * clientWidth);
      setThumbLeft((scrollLeft / scrollWidth) * clientWidth);
    }
  }, []);

  useEffect(() => {
    const viewport = viewportRef.current;
    if (!viewport) return;

    updateThumbs();
    viewport.addEventListener('scroll', updateThumbs);
    const ro = new ResizeObserver(updateThumbs);
    ro.observe(viewport);

    return () => {
      viewport.removeEventListener('scroll', updateThumbs);
      ro.disconnect();
    };
  }, [updateThumbs]);

  useEffect(() => {
    if (!isDragging) return;

    const onMove = (e: MouseEvent) => {
      const viewport = viewportRef.current;
      if (!viewport) return;

      if (isDragging === 'vertical') {
        const rect = viewport.getBoundingClientRect();
        const y = e.clientY - rect.top - thumbHeight / 2;
        const ratio = y / (rect.height - thumbHeight);
        viewport.scrollTop = ratio * (viewport.scrollHeight - viewport.clientHeight);
      } else {
        const rect = viewport.getBoundingClientRect();
        const x = e.clientX - rect.left - thumbWidth / 2;
        const ratio = x / (rect.width - thumbWidth);
        viewport.scrollLeft = ratio * (viewport.scrollWidth - viewport.clientWidth);
      }
    };

    const onUp = () => setIsDragging(null);

    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);
    return () => {
      window.removeEventListener('mousemove', onMove);
      window.removeEventListener('mouseup', onUp);
    };
  }, [isDragging, thumbHeight, thumbWidth]);

  return (
    <div className={`ctp-scroll-area ${className}`} style={style}>
      <div ref={viewportRef} className="ctp-scroll-area__viewport">
        {children}
      </div>
      {showVertical && (
        <div
          className="ctp-scroll-area__scrollbar ctp-scroll-area__scrollbar--vertical"
          style={{ opacity: isDragging === 'vertical' ? 1 : 0.6 }}
        >
          <div
            ref={verticalThumbRef}
            className="ctp-scroll-area__thumb"
            style={{ height: thumbHeight, transform: `translateY(${thumbTop}px)` }}
            onMouseDown={() => setIsDragging('vertical')}
          />
        </div>
      )}
      {showHorizontal && (
        <div
          className="ctp-scroll-area__scrollbar ctp-scroll-area__scrollbar--horizontal"
          style={{ opacity: isDragging === 'horizontal' ? 1 : 0.6 }}
        >
          <div
            ref={horizontalThumbRef}
            className="ctp-scroll-area__thumb"
            style={{ width: thumbWidth, transform: `translateX(${thumbLeft}px)` }}
            onMouseDown={() => setIsDragging('horizontal')}
          />
        </div>
      )}
      {showVertical && showHorizontal && <div className="ctp-scroll-area__corner" />}
    </div>
  );
};

ScrollArea.displayName = 'ScrollArea';
