// packages/angular/src/steps.component.ts
import { Component, input, output, computed } from '@angular/core';

type StepsVariant = 'timeline' | 'carousel';
type StepsColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';

@Component({
  selector: 'ctp-steps',
  standalone: true,
  template: `
    @if (variant() === 'carousel') {
      <div [class]="'ctp-steps-carousel ctp-steps--' + color()">
        @for (i of stepIndexes(); track i) {
          <button
            [class]="'ctp-steps-carousel-dot ' + (i === currentStep() ? 'ctp-steps-carousel-dot--active' : '')"
            (click)="onStepClick(i)"
            [attr.aria-label]="'Go to step ' + (i + 1)"
          ></button>
        }
      </div>
    }

    @if (variant() === 'timeline') {
      <div
        [class]="'ctp-steps-timeline ' + (orientation() === 'vertical' ? 'ctp-steps-timeline--vertical' : 'ctp-steps-timeline--horizontal') + ' ctp-steps--' + color()"
      >
        <div class="ctp-steps-track">
          <div
            class="ctp-steps-progress"
            [style.width.%]="orientation() === 'horizontal' ? progressWidth() : null"
            [style.height.%]="orientation() === 'vertical' ? progressWidth() : null"
          ></div>
        </div>

        @for (i of stepIndexes(); track i) {
          <button
            [class]="getItemClass(i)"
            (click)="onStepClick(i)"
            [attr.aria-label]="'Step ' + (i + 1)"
          >
            <div class="ctp-steps-dot"></div>
            @if (labels() && labels()[i]) {
              <span class="ctp-steps-label">{{ labels()[i] }}</span>
            }
          </button>
        }
      </div>
    }
  `
})
export class StepsComponent {
  currentStep = input<number>(0);
  stepsCount = input<number>(0);
  labels = input<string[]>([]);
  variant = input<StepsVariant>('timeline');
  color = input<StepsColor>('mauve');
  orientation = input<'horizontal' | 'vertical'>('horizontal');

  changeStep = output<number>();

  stepIndexes = computed(() => Array.from({ length: this.stepsCount() }, (_, i) => i));

  progressWidth = computed(() => {
    const count = this.stepsCount();
    if (count <= 1) return 0;
    return (this.currentStep() / (count - 1)) * 100;
  });

  onStepClick(index: number): void {
    this.changeStep.emit(index);
  }

  getItemClass(index: number): string {
    const isActive = index === this.currentStep();
    const isCompleted = index < this.currentStep();
    return [
      'ctp-steps-item',
      isActive ? 'ctp-steps-item--active' : '',
      isCompleted ? 'ctp-steps-item--completed' : ''
    ]
      .filter(Boolean)
      .join(' ');
  }
}

// packages/react/src/Steps.tsx
import React from 'react';

export type StepsVariant = 'timeline' | 'carousel';
export type StepsColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';

export interface StepsProps {
  currentStep: number;
  stepsCount: number;
  labels?: string[];
  variant?: StepsVariant;
  color?: StepsColor;
  onChangeStep?: (step: number) => void;
  orientation?: 'horizontal' | 'vertical';
}

export const Steps: React.FC<StepsProps> = ({
  currentStep,
  stepsCount,
  labels = [],
  variant = 'timeline',
  color = 'mauve',
  onChangeStep,
  orientation = 'horizontal',
}) => {
  const handleStepClick = (index: number) => {
    if (onChangeStep) {
      onChangeStep(index);
    }
  };

  const stepsClass = `ctp-steps--${color}`;

  if (variant === 'carousel') {
    return (
      <div className={`ctp-steps-carousel ${stepsClass}`}>
        {Array.from({ length: stepsCount }).map((_, index) => (
          <button
            key={index}
            className={`ctp-steps-carousel-dot ${index === currentStep ? 'ctp-steps-carousel-dot--active' : ''}`}
            onClick={() => handleStepClick(index)}
            aria-label={`Go to step ${index + 1}`}
          />
        ))}
      </div>
    );
  }

  // timeline variant
  const isVertical = orientation === 'vertical';
  const progressWidth = stepsCount > 1 ? (currentStep / (stepsCount - 1)) * 100 : 0;
  const progressStyle = isVertical
    ? { height: `${progressWidth}%` }
    : { width: `${progressWidth}%` };

  const timelineClasses = [
    'ctp-steps-timeline',
    isVertical ? 'ctp-steps-timeline--vertical' : 'ctp-steps-timeline--horizontal',
    stepsClass,
  ].join(' ');

  return (
    <div className={timelineClasses}>
      <div className="ctp-steps-track">
        <div
          className="ctp-steps-progress"
          style={progressStyle}
        />
      </div>

      {Array.from({ length: stepsCount }).map((_, index) => {
        const isActive = index === currentStep;
        const isCompleted = index < currentStep;
        const itemClass = [
          'ctp-steps-item',
          isActive ? 'ctp-steps-item--active' : '',
          isCompleted ? 'ctp-steps-item--completed' : '',
        ]
          .filter(Boolean)
          .join(' ');

        return (
          <button
            key={index}
            className={itemClass}
            onClick={() => handleStepClick(index)}
            aria-label={`Step ${index + 1}`}
          >
            <div className="ctp-steps-dot" />
            {labels[index] && <span className="ctp-steps-label">{labels[index]}</span>}
          </button>
        );
      })}
    </div>
  );
};
