// packages/vue/src/StepsSlider.vue
<template>
  <div class="ctp-steps-content-wrapper">
    <div
      class="ctp-steps-content-stage"
      :style="{ transform: `translateX(-${currentStep * 100}%)` }"
    >
      <div
        v-for="(node, index) in slides"
        :key="index"
        :class="['ctp-steps-content-slide', { 'ctp-steps-content-slide--active': index === currentStep }]"
      >
        <component :is="node" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useSlots, computed } from 'vue';

interface Props {
  currentStep: number;
}

defineProps<Props>();

const slots = useSlots();

const slides = computed(() => {
  if (!slots.default) return [];
  const rawChildren = slots.default();
  return rawChildren.flatMap(child => {
    if (child.type && typeof child.type === 'symbol' && child.type.description === 'v-fgt' && Array.isArray(child.children)) {
      return child.children;
    }
    return child;
  });
});
</script>

// packages/react/src/StepsSlider.tsx
import React from 'react';

export interface StepsSliderProps {
  currentStep: number;
  children: React.ReactNode;
}

export const StepsSlider: React.FC<StepsSliderProps> = ({ currentStep, children }) => {
  const childrenArray = React.Children.toArray(children);

  return (
    <div className="ctp-steps-content-wrapper">
      <div
        className="ctp-steps-content-stage"
        style={{ transform: `translateX(-${currentStep * 100}%)` }}
      >
        {childrenArray.map((child, index) => (
          <div
            key={index}
            className={`ctp-steps-content-slide ${
              index === currentStep ? 'ctp-steps-content-slide--active' : ''
            }`}
          >
            {child}
          </div>
        ))}
      </div>
    </div>
  );
};
