// packages/vue/src/Tooltip.vue
<template>
  <div
    style="position:relative;display:inline-flex"
    @mouseenter="onMouseEnter"
    @mouseleave="onMouseLeave"
    @focusin="onFocus"
    @focusout="onBlur"
  >
    <slot />
    <Teleport to="body" v-if="isVisible">
      <div
        :class="tooltipClass"
        style="position:fixed;z-index:1100"
        role="tooltip"
      >
        <div class="ctp-tooltip__content">{{ content }}</div>
        <div class="ctp-tooltip__arrow"></div>
      </div>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';

type TooltipPlacement = 'top' | 'bottom' | 'left' | 'right';

interface Props {
  content: string;
  placement?: TooltipPlacement;
  color?: string;
  delay?: number;
}

const props = withDefaults(defineProps<Props>(), {
  placement: 'top',
  color: 'dark',
  delay: 200,
});

const isVisible = ref(false);
let timeoutId: ReturnType<typeof setTimeout> | null = null;

const tooltipClass = computed(() => {
  const colorClass = props.color === 'dark' || props.color === 'light'
    ? `ctp-tooltip--preset-${props.color}`
    : `ctp-tooltip--${props.color}`;
  return [
    'ctp-tooltip',
    `ctp-tooltip--placement-${props.placement}`,
    colorClass,
  ];
});

function onMouseEnter() {
  if (timeoutId) clearTimeout(timeoutId);
  timeoutId = setTimeout(() => { isVisible.value = true; }, props.delay);
}

function onMouseLeave() {
  if (timeoutId) clearTimeout(timeoutId);
  isVisible.value = false;
}

function onFocus() {
  if (timeoutId) clearTimeout(timeoutId);
  isVisible.value = true;
}

function onBlur() {
  if (timeoutId) clearTimeout(timeoutId);
  isVisible.value = false;
}
</script>

// packages/react/src/Tooltip.tsx
import React, { useState, useRef, useEffect, ReactNode } from 'react';
import ReactDOM from 'react-dom';
import { usePortalPosition, Placement } from './usePortalPosition';
import { ButtonColor } from './Button';

export interface TooltipProps {
  content: ReactNode;
  children: React.ReactElement;
  placement?: Placement;
  offset?: number;
  color?: ButtonColor | 'dark' | 'light';
  delay?: number;
  isOpen?: boolean;
  autoFlip?: boolean;
  className?: string;
}

export const Tooltip: React.FC<TooltipProps> = ({
  content,
  children,
  placement = 'top',
  offset = 8,
  color = 'dark',
  delay = 200,
  isOpen: controlledIsOpen,
  autoFlip = true,
  className = '',
}) => {
  const [uncontrolledIsOpen, setUncontrolledIsOpen] = useState(false);
  const isControlled = controlledIsOpen !== undefined;
  const isOpen = isControlled ? controlledIsOpen : uncontrolledIsOpen;

  const triggerRef = useRef<HTMLElement>(null);
  const floatingRef = useRef<HTMLDivElement>(null);
  const timeoutId = useRef<NodeJS.Timeout>();

  const setOpen = (open: boolean) => {
    if (!isControlled) {
      setUncontrolledIsOpen(open);
    }
  };

  const handleMouseEnter = (e: React.MouseEvent) => {
    if (children.props.onMouseEnter) children.props.onMouseEnter(e);
    clearTimeout(timeoutId.current);
    timeoutId.current = setTimeout(() => {
      setOpen(true);
    }, delay);
  };

  const handleMouseLeave = (e: React.MouseEvent) => {
    if (children.props.onMouseLeave) children.props.onMouseLeave(e);
    clearTimeout(timeoutId.current);
    setOpen(false);
  };

  const handleFocus = (e: React.FocusEvent) => {
    if (children.props.onFocus) children.props.onFocus(e);
    clearTimeout(timeoutId.current);
    setOpen(true);
  };

  const handleBlur = (e: React.FocusEvent) => {
    if (children.props.onBlur) children.props.onBlur(e);
    clearTimeout(timeoutId.current);
    setOpen(false);
  };

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      clearTimeout(timeoutId.current);
    };
  }, []);

  const { top, left, actualPlacement } = usePortalPosition(triggerRef, floatingRef, {
    isOpen,
    placement,
    offset,
    autoFlip,
  });

  // Attach event handlers and refs to children
  const triggerEl = React.isValidElement(children)
    ? React.cloneElement(children as React.ReactElement<any>, {
        ref: triggerRef,
        onMouseEnter: handleMouseEnter,
        onMouseLeave: handleMouseLeave,
        onFocus: handleFocus,
        onBlur: handleBlur,
      })
    : children;

  const colorClass = color === 'dark' || color === 'light'
    ? `ctp-tooltip--preset-${color}`
    : `ctp-tooltip--${color}`;

  return (
    <>
      {triggerEl}
      {isOpen &&
        ReactDOM.createPortal(
          <div
            ref={floatingRef}
            className={`ctp-tooltip ctp-tooltip--placement-${actualPlacement} ${colorClass} ${className}`}
            style={{
              position: 'fixed',
              top: `${top}px`,
              left: `${left}px`,
              zIndex: 1100,
            }}
            role="tooltip"
          >
            <div className="ctp-tooltip__content">{content}</div>
            <div className="ctp-tooltip__arrow" />
          </div>,
          document.body
        )}
    </>
  );
};
