// packages/angular/src/avatar.component.ts
import { Component, input, signal } from '@angular/core';

type AvatarSize = 'sm' | 'md' | 'lg' | 'xl';

@Component({
  selector: 'ctp-avatar',
  standalone: true,
  template: `
    <div class="ctp-avatar" [attr.data-size]="size()" [attr.aria-label]="alt() || fallback() || 'Avatar'">
      @if (src() && !imgError()) {
        <img [src]="src()" [alt]="alt()" (error)="onError()" />
      } @else {
        <span class="ctp-avatar__fallback">{{ initials() }}</span>
      }
    </div>
  `
})
export class AvatarComponent {
  src = input<string>('');
  alt = input<string>('');
  fallback = input<string>('');
  size = input<AvatarSize>('md');

  private imgHasError = signal(false);

  imgError = this.imgHasError.asReadonly();

  initials(): string {
    const fb = this.fallback();
    if (!fb) return '?';
    if (fb.length <= 2) return fb;
    return fb
      .split(' ')
      .map(w => w[0])
      .join('')
      .toUpperCase()
      .slice(0, 2);
  }

  onError(): void {
    this.imgHasError.set(true);
  }
}

@Component({
  selector: 'ctp-avatar-group',
  standalone: true,
  template: `
    <div class="ctp-avatar-group" [attr.data-size]="size()">
      @for (item of visibleItems; track item) {
        <ng-content select="ctp-avatar" />
      }
      @if (remaining > 0) {
        <span class="ctp-avatar-group__more" [style]="moreStyle">
          +{{ remaining }}
        </span>
      }
    </div>
  `
})
export class AvatarGroupComponent {
  size = input<AvatarSize>('md');
  max = input<number | undefined>(undefined);
  remaining = 0;

  get visibleItems(): number[] {
    return [];
  }

  get moreStyle(): Record<string, string> {
    const s = this.size();
    const px = s === 'sm' ? '28px' : s === 'lg' ? '48px' : '36px';
    return { width: px, height: px };
  }
}

// packages/vue/src/Avatar.vue
<template>
  <div class="ctp-avatar" :data-size="size" :aria-label="alt || fallback || 'Avatar'">
    <img v-if="src && !imgError" :src="src" :alt="alt" @error="imgError = true" />
    <span v-else class="ctp-avatar__fallback">{{ initials }}</span>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';

type AvatarSize = 'sm' | 'md' | 'lg' | 'xl';

interface Props {
  src?: string;
  alt?: string;
  fallback?: string;
  size?: AvatarSize;
}

const props = withDefaults(defineProps<Props>(), {
  size: 'md',
});

const imgError = ref(false);

const initials = computed(() => {
  if (!props.fallback) return '?';
  if (props.fallback.length <= 2) return props.fallback;
  return props.fallback
    .split(' ')
    .map(w => w[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);
});
</script>
