// packages/react/src/Carousel.tsx
import React, { useState, useRef, useCallback, useEffect } from 'react';

export interface CarouselProps {
  children: React.ReactNode;
  showArrows?: boolean;
  showDots?: boolean;
  autoPlay?: boolean;
  autoPlayInterval?: number;
  className?: string;
}

export const Carousel: React.FC<CarouselProps> = ({
  children,
  showArrows = true,
  showDots = true,
  autoPlay = false,
  autoPlayInterval = 4000,
  className = '',
}) => {
  const [current, setCurrent] = useState(0);
  const trackRef = useRef<HTMLDivElement>(null);
  const intervalRef = useRef<ReturnType<typeof setInterval>>();

  const slides = React.Children.toArray(children).filter(Boolean);
  const total = slides.length;

  const goTo = useCallback((index: number) => {
    setCurrent(Math.max(0, Math.min(index, total - 1)));
  }, [total]);

  const prev = useCallback(() => goTo(current - 1), [current, goTo]);
  const next = useCallback(() => goTo(current + 1), [current, goTo]);

  useEffect(() => {
    if (autoPlay && total > 1) {
      intervalRef.current = setInterval(next, autoPlayInterval);
      return () => clearInterval(intervalRef.current);
    }
  }, [autoPlay, autoPlayInterval, total, next]);

  if (total === 0) return null;

  return (
    <div className={`ctp-carousel ${className}`} role="region" aria-label="Carousel">
      <div className="ctp-carousel__viewport">
        <div
          ref={trackRef}
          className="ctp-carousel__track"
          style={{ transform: `translateX(-${current * 100}%)` }}
        >
          {slides.map((slide, i) => (
            <div key={i} className="ctp-carousel__slide" role="group" aria-roledescription="slide" aria-label={`Slide ${i + 1} of ${total}`}>
              {slide}
            </div>
          ))}
        </div>
      </div>
      {showArrows && total > 1 && (
        <>
          <button className="ctp-carousel__btn ctp-carousel__btn--prev" onClick={prev} aria-label="Previous slide" disabled={current === 0}>
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="15 18 9 12 15 6" />
            </svg>
          </button>
          <button className="ctp-carousel__btn ctp-carousel__btn--next" onClick={next} aria-label="Next slide" disabled={current === total - 1}>
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="9 18 15 12 9 6" />
            </svg>
          </button>
        </>
      )}
      {showDots && total > 1 && (
        <div className="ctp-carousel__dots" role="tablist" aria-label="Slides">
          {slides.map((_, i) => (
            <button
              key={i}
              className={`ctp-carousel__dot${i === current ? ' ctp-carousel__dot--active' : ''}`}
              onClick={() => goTo(i)}
              role="tab"
              aria-selected={i === current}
              aria-label={`Go to slide ${i + 1}`}
            />
          ))}
        </div>
      )}
    </div>
  );
};

Carousel.displayName = 'Carousel';

// packages/vue/src/Carousel.vue
<template>
  <div class="ctp-carousel" role="region" aria-label="Carousel">
    <div class="ctp-carousel__viewport">
      <div class="ctp-carousel__track" :style="{ transform: `translateX(-${current * 100}%)` }">
        <div
          v-for="(_, i) in slides"
          :key="i"
          class="ctp-carousel__slide"
          role="group"
          aria-roledescription="slide"
          :aria-label="`Slide ${i + 1} of ${slides.length}`"
        >
          <slot />
        </div>
      </div>
    </div>
    <button
      v-if="showArrows && slides.length > 1"
      class="ctp-carousel__btn ctp-carousel__btn--prev"
      :disabled="current === 0"
      @click="prev"
      aria-label="Previous slide"
    >
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
        <polyline points="15 18 9 12 15 6" />
      </svg>
    </button>
    <button
      v-if="showArrows && slides.length > 1"
      class="ctp-carousel__btn ctp-carousel__btn--next"
      :disabled="current === slides.length - 1"
      @click="next"
      aria-label="Next slide"
    >
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
        <polyline points="9 18 15 12 9 6" />
      </svg>
    </button>
    <div v-if="showDots && slides.length > 1" class="ctp-carousel__dots" role="tablist" aria-label="Slides">
      <button
        v-for="(_, i) in slides"
        :key="i"
        :class="['ctp-carousel__dot', { 'ctp-carousel__dot--active': i === current }]"
        @click="goTo(i)"
        role="tab"
        :aria-selected="i === current"
        :aria-label="`Go to slide ${i + 1}`"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, useSlots, computed, onMounted, onUnmounted } from 'vue';

interface Props {
  showArrows?: boolean;
  showDots?: boolean;
  autoPlay?: boolean;
  autoPlayInterval?: number;
}

const props = withDefaults(defineProps<Props>(), {
  showArrows: true,
  showDots: true,
  autoPlay: false,
  autoPlayInterval: 4000,
});

const slots = useSlots();
const slides = computed(() => (slots.default?.() || []).filter(Boolean));

const current = ref(0);
let intervalId: ReturnType<typeof setInterval> | null = null;

function goTo(index: number) {
  current.value = Math.max(0, Math.min(index, slides.value.length - 1));
}

function prev() { goTo(current.value - 1); }
function next() { goTo(current.value + 1); }

onMounted(() => {
  if (props.autoPlay && slides.value.length > 1) {
    intervalId = setInterval(next, props.autoPlayInterval);
  }
});

onUnmounted(() => {
  if (intervalId) clearInterval(intervalId);
});
</script>
