// packages/angular/src/checkbox.component.ts
import { Component, input, computed, model, forwardRef } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { FormControlColor, getFormThemeClass } from './form-types';

@Component({
  selector: 'ctp-checkbox',
  standalone: true,
  template: `
    <label class="ctp-checkbox-row" [attr.data-state]="disabled() ? 'disabled' : null" [attr.data-color]="color()">
      <input
        type="checkbox"
        [disabled]="disabled()"
        [checked]="checked()"
        (change)="onToggle()"
      />
      <span class="ctp-checkbox-box">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
          <polyline points="20 6 9 17 4 12"></polyline>
        </svg>
      </span>
      <span>{{ label() }}</span>
    </label>
  `,
  providers: [{
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => CheckboxComponent),
    multi: true,
  }],
})
export class CheckboxComponent implements ControlValueAccessor {
  checked = model<boolean>(false);
  label = input.required<string>();
  disabled = input<boolean>(false);
  color = input<FormControlColor>('mauve');

  private _onChange: (val: any) => void = () => {};
  private _onTouched: () => void = () => {};



  writeValue(val: any): void { this.checked.set(!!val); }
  registerOnChange(fn: any): void { this._onChange = fn; }
  registerOnTouched(fn: any): void { this._onTouched = fn; }
  setDisabledState(isDisabled: boolean): void {}

  onToggle(): void {
    const next = !this.checked();
    this.checked.set(next);
    this._onChange(next);
    this._onTouched();
  }
}

// packages/vue/src/Checkbox.vue
<template>
  <label class="ctp-checkbox-row" :data-state="disabled ? 'disabled' : undefined" :data-color="color">
    <input
      type="checkbox"
      :disabled="disabled"
      :checked="modelValue"
      @change="onToggle"
    />
    <span class="ctp-checkbox-box">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
        <polyline points="20 6 9 17 4 12"></polyline>
      </svg>
    </span>
    <span>{{ label }}</span>
  </label>
</template>

<script setup lang="ts">


type FormControlColor =
  | 'rosewater' | 'flamingo' | 'pink' | 'mauve' | 'red' | 'maroon'
  | 'peach' | 'yellow' | 'green' | 'teal' | 'sky' | 'sapphire'
  | 'blue' | 'lavender';

interface Props {
  label: string;
  modelValue?: boolean;
  disabled?: boolean;
  color?: FormControlColor;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: false,
  disabled: false,
  color: 'mauve',
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void;
}>();

const getFormThemeClass = (color: FormControlColor) => `ctp-form--${color}`;



function onToggle() {
  emit('update:modelValue', !props.modelValue);
}
</script>
