// packages/react/src/Skeleton.tsx
import React from 'react';

export type SkeletonVariant = 'text' | 'circle' | 'rect';
export type SkeletonSize = 'sm' | 'md' | 'lg' | 'xl';

export interface SkeletonProps {
  variant?: SkeletonVariant;
  size?: SkeletonSize;
  width?: string | number;
  height?: string | number;
  className?: string;
  animated?: boolean;
  count?: number;
  gap?: string | number;
  children?: React.ReactNode;
}

export const Skeleton: React.FC<SkeletonProps> = ({
  variant = 'text',
  size = 'md',
  width,
  height,
  className = '',
  animated = true,
  count = 1,
  gap = '8px',
  children,
}) => {
  const classes = [
    'ctp-skeleton',
    `ctp-skeleton--${variant}`,
    `ctp-skeleton--${size}`,
    !animated ? 'ctp-skeleton--no-animation' : '',
    width ? '' : 'ctp-skeleton--full',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const style: React.CSSProperties = {};
  if (width) style.width = width;
  if (height) style.height = height;

  if (children) {
    return (
      <span className={classes} style={style} aria-hidden="true">
        {children}
      </span>
    );
  }

  if (count > 1) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap }}>
        {Array.from({ length: count }).map((_, i) => (
          <div key={i} className={classes} style={style} aria-hidden="true" />
        ))}
      </div>
    );
  }

  return <div className={classes} style={style} aria-hidden="true" />;
};

Skeleton.displayName = 'Skeleton';

// packages/vue/src/Skeleton.vue
<template>
  <div v-if="count > 1" class="ctp-skeleton-group" :style="{ gap }">
    <div
      v-for="i in count"
      :key="i"
      :class="classes"
      :style="customStyle"
      aria-hidden="true"
    />
  </div>
  <div v-else :class="classes" :style="customStyle" aria-hidden="true">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

type SkeletonVariant = 'text' | 'circle' | 'rect';
type SkeletonSize = 'sm' | 'md' | 'lg' | 'xl';

interface Props {
  variant?: SkeletonVariant;
  size?: SkeletonSize;
  width?: string;
  height?: string;
  animated?: boolean;
  count?: number;
  gap?: string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'text',
  size: 'md',
  animated: true,
  count: 1,
  gap: '8px',
});

const classes = computed(() => {
  const c = [
    'ctp-skeleton',
    `ctp-skeleton--${props.variant}`,
    `ctp-skeleton--${props.size}`,
    !props.animated ? 'ctp-skeleton--no-animation' : '',
    props.width ? '' : 'ctp-skeleton--full',
  ];
  return c.filter(Boolean).join(' ');
});

const customStyle = computed(() => {
  const style: Record<string, string> = {};
  if (props.width) style.width = props.width;
  if (props.height) style.height = props.height;
  return style;
});
</script>

<style scoped>
.ctp-skeleton-group {
  display: flex;
  flex-direction: column;
}
</style>
