// packages/react/src/Tile.tsx
import React from 'react';

export type TileVariant = 'flat' | 'elevated' | 'outline' | 'tonal' | 'colored';
export type TileSize = 'sm' | 'md' | 'lg';
export type TileShape = 'square' | 'rounded' | 'pill';
export type TileOrientation = 'horizontal' | 'vertical' | 'vertical-center';
export type TileIndicator = 'none' | 'top' | 'bottom' | 'left' | 'right';
export type TileColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';

export interface TileProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: TileVariant;
  size?: TileSize;
  shape?: TileShape;
  orientation?: TileOrientation;
  color?: TileColor;
  indicator?: TileIndicator;
  isInteractive?: boolean;
  isSelected?: boolean;
  isDisabled?: boolean;
  icon?: React.ReactNode;
  title?: React.ReactNode;
  subtitle?: React.ReactNode;
  meta?: React.ReactNode;
}

export const Tile: React.FC<TileProps> = ({
  variant = 'flat',
  size = 'md',
  shape = 'rounded',
  orientation = 'horizontal',
  color = 'mauve',
  indicator = 'none',
  isInteractive = false,
  isSelected = false,
  isDisabled = false,
  icon,
  title,
  subtitle,
  meta,
  className = '',
  children,
  ...props
}) => {
  const classNames = [
    'ctp-tile',
    `ctp-tile--${variant}`,
    `ctp-tile--${size}`,
    `ctp-tile--${shape}`,
    `ctp-tile--${orientation}`,
    color ? `ctp-tile--${color}` : '',
    indicator !== 'none' ? `ctp-tile--indicator-${indicator}` : '',
    isInteractive ? 'ctp-tile--interactive' : '',
    isSelected ? 'ctp-tile--selected' : '',
    isDisabled ? 'ctp-tile--disabled' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classNames} {...props}>
      {children ? (
        children
      ) : (
        <>
          {icon && <div className="ctp-tile__icon">{icon}</div>}
          {(title || subtitle) && (
            <div className="ctp-tile__content">
              {title && <span className="ctp-tile__title">{title}</span>}
              {subtitle && <span className="ctp-tile__subtitle">{subtitle}</span>}
            </div>
          )}
          {meta && <div className="ctp-tile__meta">{meta}</div>}
        </>
      )}
    </div>
  );
};

Tile.displayName = 'Tile';

// packages/vue/src/Tile.vue
<template>
  <div :class="tileClass" v-bind="$attrs">
    <slot>
      <div v-if="$slots.icon || icon" class="ctp-tile__icon">
        <slot name="icon">{{ icon }}</slot>
      </div>

      <div v-if="$slots.content || title || subtitle" class="ctp-tile__content">
        <slot name="content">
          <span v-if="title" class="ctp-tile__title">{{ title }}</span>
          <span v-if="subtitle" class="ctp-tile__subtitle">{{ subtitle }}</span>
        </slot>
      </div>

      <div v-if="$slots.meta || meta" class="ctp-tile__meta">
        <slot name="meta">{{ meta }}</slot>
      </div>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

type TileVariant = 'flat' | 'elevated' | 'outline' | 'tonal' | 'colored';
type TileSize = 'sm' | 'md' | 'lg';
type TileShape = 'square' | 'rounded' | 'pill';
type TileOrientation = 'horizontal' | 'vertical' | 'vertical-center';
type TileIndicator = 'none' | 'top' | 'bottom' | 'left' | 'right';
type TileColor =
  | 'rosewater'
  | 'flamingo'
  | 'pink'
  | 'mauve'
  | 'red'
  | 'maroon'
  | 'peach'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'sky'
  | 'sapphire'
  | 'blue'
  | 'lavender';

interface Props {
  variant?: TileVariant;
  size?: TileSize;
  shape?: TileShape;
  orientation?: TileOrientation;
  color?: TileColor;
  indicator?: TileIndicator;
  isInteractive?: boolean;
  isSelected?: boolean;
  isDisabled?: boolean;
  icon?: any;
  title?: string;
  subtitle?: string;
  meta?: string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'flat',
  size: 'md',
  shape: 'rounded',
  orientation: 'horizontal',
  color: 'mauve',
  indicator: 'none',
  isInteractive: false,
  isSelected: false,
  isDisabled: false,
});

const tileClass = computed(() => {
  return [
    'ctp-tile',
    `ctp-tile--${props.variant}`,
    `ctp-tile--${props.size}`,
    `ctp-tile--${props.shape}`,
    `ctp-tile--${props.orientation}`,
    props.color ? `ctp-tile--${props.color}` : '',
    props.indicator !== 'none' ? `ctp-tile--indicator-${props.indicator}` : '',
    props.isInteractive ? 'ctp-tile--interactive' : '',
    props.isSelected ? 'ctp-tile--selected' : '',
    props.isDisabled ? 'ctp-tile--disabled' : '',
  ];
});
</script>
